(function(){
'use strict';
var OVERRIDES={
  lament:{sentence:'Economists continue to ____ the decline of small retailers in towns dominated by online commerce.',choices:['lament','bolster','curtail','rectify']},
  spar:{sentence:'The two candidates began to ____ over tax policy during the televised debate.',choices:['spar','assuage','emulate','substantiate']},
  torment:{sentence:'For years, uncertainty about her missing brother was a source of constant ____.',choices:['torment','clemency','hindsight','solvency']},
  eccentric:{sentence:'The inventor was known for his ____ habit of holding meetings at dawn in the city park.',choices:['eccentric','pungent','gaunt','pristine']},
  ornate:{sentence:'Conservators spent months restoring the ____ ceiling, which was covered in gold leaf and intricate carvings.',choices:['ornate','austere','capricious','laconic']},
  percolate:{sentence:'It took several years for concerns raised by junior staff to ____ up to senior management.',choices:['percolate','abate','concede','wane']},
  contort:{sentence:'The acrobat could ____ her body into positions that seemed impossible.',choices:['contort','alleviate','elicit','perpetuate']},
  tarnish:{sentence:'A single ethics violation could ____ the judge\'s otherwise distinguished reputation.',choices:['tarnish','assuage','bolster','rectify']},
  gratify:{sentence:'The enthusiastic response from readers will ____ the researchers who spent years on the study.',choices:['gratify','censure','emulate','substantiate']},
  translucent:{sentence:'The architect installed ____ panels that allowed daylight in while preserving privacy.',choices:['translucent','austere','capricious','laconic']},
  pampered:{sentence:'The ____ heir had never held a job, taken public transportation, or prepared his own meals.',choices:['pampered','translucent','gaunt','contiguous']},
  scamper:{sentence:'At the first sound of thunder, the children began to ____ toward the shelter.',choices:['scamper','assuage','bolster','rectify']},
  belittle:{sentence:'Managers who regularly ____ junior employees undermine trust throughout the organization.',choices:['belittle','alleviate','elicit','perpetuate']},
  rotund:{sentence:'The actor wore padding to appear ____ for the role of a well-fed merchant.',choices:['rotund','austere','capricious','laconic']},
  intangible:{sentence:'Employee morale is an ____ asset that can strongly influence productivity.',choices:['intangible','austere','capricious','laconic']},
  mutinous:{sentence:'The captain confined several ____ sailors who had refused to follow orders.',choices:['mutinous','austere','capricious','laconic']},
  subversive:{sentence:'The regime banned the novel, claiming that its criticism of authority was ____.',choices:['subversive','austere','capricious','laconic']},
  impromptu:{sentence:'The mayor gave an ____ speech after unexpectedly being invited onto the stage.',choices:['impromptu','austere','capricious','laconic']},
  provincial:{sentence:'The museum aims to bring major international exhibitions to ____ cities that rarely host them.',choices:['provincial','austere','capricious','laconic']},
  contiguous:{sentence:'The proposed park would combine three ____ parcels into a single protected area.',choices:['contiguous','austere','capricious','laconic']},
  pristine:{sentence:'Researchers discovered a ____ coral reef that showed almost no sign of human disturbance.',choices:['pristine','austere','capricious','laconic']},
  heedless:{sentence:'The company expanded rapidly, seemingly ____ of repeated warnings about its mounting debt.',choices:['heedless','austere','capricious','laconic']},
  purge:{sentence:'The new chair promised to ____ fraudulent accounts from the membership database.',choices:['purge','assuage','emulate','substantiate']},
  revert:{sentence:'If negotiations fail, the tariff rate will ____ to its previous level in January.',choices:['revert','abate','concede','wane']},
  discretion:{sentence:'Judges retain considerable ____ when deciding whether to impose the maximum sentence.',choices:['discretion','grievance','hindsight','notoriety']},
  acclimate:{sentence:'New recruits are given two weeks to ____ to the extreme heat before beginning field exercises.',choices:['acclimate','assuage','bolster','rectify']},
  deify:{sentence:'Authoritarian propaganda often seeks to ____ a leader and portray every decision as infallible.',choices:['deify','censure','emulate','substantiate']},
  ferment:{sentence:'The brewer allows the mixture to ____ in sealed tanks before bottling the beverage.',choices:['ferment','abate','concede','wane']},
  suave:{sentence:'The diplomat\'s ____ manner helped ease tensions during the difficult negotiations.',choices:['suave','austere','capricious','laconic']},
  enigma:{sentence:'Despite years of investigation, the sudden disappearance of the vessel remains an ____.',choices:['enigma','convergence','clemency','fortitude']},
  exuberant:{sentence:'Supporters poured into the streets in an ____ celebration after the election result was announced.',choices:['exuberant','austere','capricious','laconic']},
  unassuming:{sentence:'Despite receiving international awards, the scientist remained ____ and rarely discussed her achievements.',choices:['unassuming','austere','capricious','laconic']},
  provision:{sentence:'A controversial ____ in the bill would allow authorities to retain the data for five years.',choices:['provision','convergence','clemency','notoriety']},
  repulse:{sentence:'The defenders managed to ____ the first assault without suffering serious losses.',choices:['repulse','alleviate','elicit','perpetuate']},
  conciliate:{sentence:'The new director met with union leaders in an effort to ____ employees angered by the layoffs.',choices:['conciliate','bolster','emulate','rectify']},
  bungle:{sentence:'Inexperienced contractors may ____ the restoration project unless experts supervise their work.',choices:['bungle','assuage','emulate','substantiate']},
  acclaim:{sentence:'The novelist won international ____ for a work that confronted the country\'s colonial past.',choices:['acclaim','grievance','hindsight','solvency']},
  bigotry:{sentence:'The campaign was condemned for exploiting religious ____ to divide voters.',choices:['bigotry','clemency','hindsight','solvency']},
  dogma:{sentence:'The professor encouraged students to challenge accepted ____ rather than repeat it uncritically.',choices:['dogma','grievance','hindsight','solvency']},
  gaunt:{sentence:'After weeks without adequate food, the rescued hikers looked exhausted and ____.',choices:['gaunt','austere','capricious','laconic']},
  meager:{sentence:'The relief agency struggled to operate on the ____ funds provided by international donors.',choices:['meager','austere','capricious','laconic']},
  bravado:{sentence:'His confident speech was mostly ____ intended to hide his anxiety about the investigation.',choices:['bravado','convergence','clemency','fortitude']},
  incarcerate:{sentence:'The regime used vague security laws to ____ journalists who criticized senior officials.',choices:['incarcerate','consolidate','perpetuate','substantiate']},
  discord:{sentence:'The dispute over migration policy created deep ____ within the governing coalition.',choices:['discord','clemency','hindsight','solvency']},
  consignment:{sentence:'Customs officers discovered counterfeit medicine hidden in a ____ of medical supplies.',choices:['consignment','grievance','hindsight','notoriety']},
  dupe:{sentence:'Fraudsters used a fake investment platform to ____ hundreds of retirees out of their savings.',choices:['dupe','censure','emulate','perpetuate']},
  pawn:{sentence:'Facing eviction, he decided to ____ his grandfather\'s watch to pay the rent.',choices:['pawn','assuage','bolster','substantiate']},
  sully:{sentence:'The corruption allegations threatened to permanently ____ the charity\'s reputation among its longtime donors.',choices:['sully','curtail','assuage','rectify']},
  liaison:{sentence:'She served as the main ____ between emergency crews and local officials during the evacuation.',choices:['liaison','convergence','clemency','notoriety']},
  thwart:{sentence:'Strong encryption helped ____ an attempt to steal confidential patient records.',choices:['thwart','assuage','emulate','substantiate']},
  elucidate:{sentence:'The report uses several case studies to ____ how weak oversight allowed the fraud to continue.',choices:['elucidate','bolster','curtail','rectify']},
  solicit:{sentence:'The committee will ____ public comments before finalizing the new environmental standards.',choices:['solicit','assuage','emulate','perpetuate']},
  emanate:{sentence:'Residents reported a chemical odor that seemed to ____ from an abandoned warehouse near the river.',choices:['emanate','abate','concede','wane']},
  consolidate:{sentence:'The merger allowed the two charities to ____ their administrative operations and reduce costs.',choices:['consolidate','alleviate','disparage','substantiate']},
  vestige:{sentence:'The crumbling watchtower is the last ____ of the fortress that once guarded the valley.',choices:['vestige','incursion','jeopardy','embezzlement']},
  pertinent:{sentence:'The judge instructed the witness to answer only questions ____ to the case.',choices:['pertinent','austere','capricious','laconic']},
  impregnable:{sentence:'The data center\'s layered defenses made it virtually ____ to both physical intrusion and cyberattack.',choices:['impregnable','austere','capricious','laconic']},
  concoct:{sentence:'Investigators concluded that the executive had tried to ____ an elaborate excuse for the missing payments.',choices:['concoct','assuage','emulate','rectify']},
  deduce:{sentence:'From the sudden drop in network traffic, engineers could ____ that the server had failed.',choices:['deduce','censure','emulate','perpetuate']},
  prevarication:{sentence:'After weeks of ____ about the budget gap, the mayor finally disclosed the actual figures.',choices:['prevarication','convergence','clemency','fortitude']},
  flout:{sentence:'Companies that openly ____ safety regulations should face substantial penalties.',choices:['flout','assuage','bolster','substantiate']},
  pungent:{sentence:'A ____ odor from the damaged pipeline forced nearby residents to evacuate.',choices:['pungent','austere','capricious','laconic']},
  incisive:{sentence:'Her ____ analysis exposed a contradiction at the heart of the government\'s proposal.',choices:['incisive','austere','capricious','laconic']},
  solvency:{sentence:'Auditors questioned the airline\'s ____ after it missed three debt payments.',choices:['solvency','clemency','hindsight','notoriety']},
  stolid:{sentence:'The defendant remained ____ as the verdict was read, displaying neither relief nor fear.',choices:['stolid','austere','capricious','laconic']},
  lackluster:{sentence:'Despite an expensive advertising campaign, the product generated ____ sales during its first quarter.',choices:['lackluster','austere','capricious','laconic']},
  backlog:{sentence:'The court hired additional clerks to reduce its growing ____ of unresolved cases.',choices:['backlog','convergence','clemency','embezzlement']},
  upheaval:{sentence:'The abrupt collapse of the coalition plunged the country into political ____.',choices:['upheaval','clemency','hindsight','embezzlement']},
  grievance:{sentence:'Employees filed a formal ____ over the company\'s refusal to pay overtime.',choices:['grievance','convergence','clemency','notoriety']},
  precocious:{sentence:'The ____ student began conducting university-level experiments at the age of twelve.',choices:['precocious','austere','capricious','laconic']},
  ascetic:{sentence:'The monk followed an ____ lifestyle, owning little more than a robe and a bowl.',choices:['ascetic','stolid','squeamish','impregnable']},
  squeamish:{sentence:'Viewers who are ____ about surgical procedures may find the documentary difficult to watch.',choices:['squeamish','austere','capricious','laconic']},
  notoriety:{sentence:'The financier gained ____ after his role in the massive tax-evasion scheme was exposed.',choices:['notoriety','clemency','hindsight','solvency']},
  fortitude:{sentence:'Rebuilding the community after the earthquake required remarkable patience and ____.',choices:['fortitude','notoriety','hindsight','embezzlement']},
  cessation:{sentence:'Negotiators called for an immediate ____ of hostilities so humanitarian aid could enter the region.',choices:['cessation','convergence','clemency','fortitude']},
  equivocate:{sentence:'Faced with a direct question about the missing funds, the minister continued to ____ rather than give a clear answer.',choices:['equivocate','bolster','curtail','rectify']},
  defer:{sentence:'Because two key witnesses were unavailable, the committee agreed to ____ its final decision until September.',choices:['defer','assuage','emulate','substantiate']},
  envoy:{sentence:'The president dispatched a special ____ to negotiate the release of the detained aid workers.',choices:['envoy','anomaly','impetus','moratorium']},
  auspicious:{sentence:'The peaceful transfer of power was seen as an ____ beginning for the young democracy.',choices:['auspicious','austere','capricious','laconic']},
  obliterate:{sentence:'A sustained cyberattack could ____ critical records unless the agency maintains secure backups.',choices:['obliterate','alleviate','engender','reconcile']},
  entail:{sentence:'Replacing the aging rail network will ____ substantial costs and years of disruption.',choices:['entail','disparage','emulate','substantiate']},
  convergence:{sentence:'The ____ of falling energy prices and higher wages helped revive consumer spending.',choices:['convergence','adversity','impetus','rancor']},
  coax:{sentence:'Negotiators managed to ____ both sides back to the table by offering a temporary ceasefire.',choices:['coax','censure','emulate','rectify']},
  perennial:{sentence:'Water scarcity remains a ____ problem in regions exposed to prolonged drought.',choices:['perennial','austere','capricious','laconic']},
  clemency:{sentence:'Human rights groups urged the governor to grant ____ to the prisoner because of new evidence.',choices:['clemency','adversity','impetus','moratorium']},
  unruly:{sentence:'Security staff removed several ____ spectators who had begun throwing objects onto the field.',choices:['unruly','austere','capricious','laconic']},
  hindsight:{sentence:'In ____, regulators should have intervened before the housing bubble grew so large.',choices:['hindsight','anomaly','impetus','moratorium']},
  quarantine:{sentence:'The infected animals were placed in ____ to prevent the disease from spreading.',choices:['quarantine','anomaly','impetus','moratorium']},
  incursion:{sentence:'The unauthorized military ____ across the border prompted an emergency meeting of the Security Council.',choices:['incursion','adversity','impetus','moratorium']},
  jeopardy:{sentence:'Delaying the repairs would place the entire flood-control system in ____.',choices:['jeopardy','adversity','impetus','moratorium']},
  appraise:{sentence:'Independent experts were hired to ____ the collection before it was insured.',choices:['appraise','alleviate','elicit','perpetuate']},
  inane:{sentence:'The interview focused on ____ gossip instead of the candidate\'s economic policies.',choices:['inane','austere','capricious','laconic']},
  wrest:{sentence:'Rebel forces tried to ____ control of the port from government troops.',choices:['wrest','assuage','bolster','substantiate']},
  caustic:{sentence:'The columnist\'s ____ criticism angered officials but drew attention to serious flaws in the policy.',choices:['caustic','austere','capricious','laconic']},
  embezzlement:{sentence:'The treasurer was convicted of ____ after secretly transferring charity funds to a personal account.',choices:['embezzlement','adversity','impetus','moratorium']},
  rife:{sentence:'The procurement process was ____ with conflicts of interest and undisclosed payments.',choices:['rife','austere','capricious','laconic']},
  invigorate:{sentence:'The central bank hoped lower borrowing costs would ____ investment in small businesses.',choices:['invigorate','assuage','disparage','perpetuate']},
  bemoan:{sentence:'Local officials often ____ the shortage of affordable housing while approving few new developments.',choices:['bemoan','bolster','emulate','rectify']},
  paramount:{sentence:'Protecting the safety of civilians must remain ____ during the evacuation.',choices:['paramount','austere','capricious','laconic']},
  implore:{sentence:'Doctors ____ residents to leave the contaminated area before conditions deteriorate.',choices:['implore','censure','emulate','substantiate']},
  abdicate:{sentence:'The board accused the CEO of trying to ____ responsibility for the failed merger.',choices:['abdicate','ascertain','articulate','appease']},
  abhor:{sentence:'Many citizens ____ the use of torture under any circumstances.',choices:['abhor','appease','amalgamate','admonish']},
  abject:{sentence:'The displaced families were living in ____ poverty after the conflict.',choices:['abject','affluent','arcane','adroit']},
  abrogate:{sentence:'The new administration threatened to ____ the treaty without consulting its allies.',choices:['abrogate','amalgamate','articulate','ascertain']},
  accolade:{sentence:'For the young scientist, the international prize was the highest ____ of her career.',choices:['accolade','alacrity','animosity','anachronism']},
  acquiesce:{sentence:'After months of resistance, the board finally agreed to ____ to the shareholders\' demands.',choices:['acquiesce','appease','articulate','ascertain']},
  admonish:{sentence:'The judge had to ____ the attorney for repeatedly interrupting the witness.',choices:['admonish','abhor','aggrandize','alienate']},
  adroit:{sentence:'Her ____ handling of the negotiations prevented a costly strike.',choices:['adroit','affable','ambivalent','arduous']},
  affable:{sentence:'Despite his senior position, the professor remained ____ and easy to approach.',choices:['affable','arcane','apprehensive','abject']},
  affluent:{sentence:'The tax incentive disproportionately benefited ____ households in the capital.',choices:['affluent','abject','arduous','ambivalent']},
  aggrandize:{sentence:'Critics accused the leader of using the emergency to ____ his own power.',choices:['aggrandize','abdicate','abrogate','amalgamate']},
  alacrity:{sentence:'She accepted the difficult overseas assignment with surprising ____.',choices:['alacrity','accolade','animosity','antipathy']},
  alienate:{sentence:'The candidate\'s harsh rhetoric may ____ moderate voters.',choices:['alienate','appease','admonish','articulate']},
  amalgamate:{sentence:'The proposal would ____ the two regional agencies into a single authority.',choices:['amalgamate','alienate','appease','aggrandize']},
  ambivalent:{sentence:'Seeing both compelling benefits and serious risks, voters remained ____ about the proposal.',choices:['ambivalent','affable','adroit','arcane']},
  amenable:{sentence:'The committee proved ____ to revising the regulations after hearing expert testimony.',choices:['amenable','affluent','arduous','abject']},
  anachronism:{sentence:'In an era of instant digital communication, the fax machine can seem like an ____.',choices:['anachronism','accolade','alacrity','animosity']},
  animosity:{sentence:'Years of territorial disputes fueled deep ____ between the neighboring states.',choices:['animosity','accolade','alacrity','anachronism']},
  antipathy:{sentence:'The journalist made no attempt to conceal her ____ toward political corruption.',choices:['antipathy','accolade','alacrity','anachronism']},
  appease:{sentence:'The government offered limited concessions to ____ the angry protesters.',choices:['appease','admonish','articulate','ascertain']},
  apprehensive:{sentence:'Investors were ____ about entering a market with such unstable regulations.',choices:['apprehensive','affable','adroit','affluent']},
  arcane:{sentence:'Only a handful of specialists understood the ____ provisions of the tax code.',choices:['arcane','affable','affluent','ambivalent']},
  arduous:{sentence:'Restoring the polluted wetland proved to be an ____ task.',choices:['arduous','affable','affluent','ambivalent']},
  articulate:{sentence:'Each candidate must ____ a coherent plan for reducing public debt.',choices:['articulate','ascertain','appease','amalgamate']},
  ascertain:{sentence:'Investigators worked to ____ whether the safety records had been falsified.',choices:['ascertain','admonish','alienate','appease']},
  astute:{sentence:'Her ____ analysis identified a risk that the other advisers had overlooked.',choices:['astute','banal','boisterous','callous']},
  atrophy:{sentence:'Without regular exercise, the muscles surrounding the injured joint may begin to ____.',choices:['atrophy','avert','cajole','coerce']},
  avarice:{sentence:'The novel portrays a banker whose ____ ultimately destroys his family and reputation.',choices:['avarice','brevity','camaraderie','catharsis']},
  avert:{sentence:'Prompt diplomatic intervention helped ____ a wider regional conflict.',choices:['avert','atrophy','cajole','coerce']},
  banal:{sentence:'The critic dismissed the speech as a collection of ____ observations and tired slogans.',choices:['banal','astute','boisterous','circumspect']},
  belie:{sentence:'The official statistics ____ claims that the economic recovery has benefited everyone.',choices:['belie','cajole','coalesce','construe']},
  bereft:{sentence:'Without independent oversight, the agency was ____ of meaningful accountability.',choices:['bereft','blatant','cogent','conciliatory']},
  blatant:{sentence:'The altered records were a ____ attempt to conceal the company\'s safety violations.',choices:['blatant','circumspect','conscientious','conciliatory']},
  boisterous:{sentence:'The teacher struggled to quiet the ____ crowd gathered outside the auditorium.',choices:['boisterous','banal','bereft','cogent']},
  brevity:{sentence:'Given the limited time, the chair praised the speaker for her ____.',choices:['brevity','avarice','camaraderie','complicity']},
  cajole:{sentence:'Lobbyists tried to ____ undecided lawmakers into supporting the controversial bill.',choices:['cajole','avert','atrophy','coalesce']},
  callous:{sentence:'The company was condemned for its ____ disregard for the welfare of displaced residents.',choices:['callous','astute','commensurate','conscientious']},
  camaraderie:{sentence:'Months of working under difficult conditions fostered strong ____ among the volunteers.',choices:['camaraderie','avarice','brevity','complicity']},
  catharsis:{sentence:'For many survivors, giving public testimony provided a sense of ____.',choices:['catharsis','avarice','brevity','conflagration']},
  circumspect:{sentence:'Diplomats remained ____ in their public comments while negotiations were still under way.',choices:['circumspect','blatant','boisterous','callous']},
  coalesce:{sentence:'Several small opposition groups began to ____ around a single reform candidate.',choices:['coalesce','avert','cajole','coerce']},
  coerce:{sentence:'The law prohibits employers from attempting to ____ workers into unpaid overtime.',choices:['coerce','avert','atrophy','coalesce']},
  cogent:{sentence:'The attorney presented a ____ argument supported by extensive documentary evidence.',choices:['cogent','banal','boisterous','callous']},
  commensurate:{sentence:'The penalty should be ____ with the seriousness of the offense.',choices:['commensurate','banal','bereft','clandestine']},
  complicity:{sentence:'Newly released documents revealed the official\'s ____ in the corruption scheme.',choices:['complicity','brevity','camaraderie','catharsis']},
  conciliatory:{sentence:'Hoping to reopen negotiations, the minister adopted a more ____ tone.',choices:['conciliatory','blatant','callous','clandestine']},
  conflagration:{sentence:'Firefighters from three provinces struggled to contain the massive ____.',choices:['conflagration','avarice','brevity','complicity']},
  conscientious:{sentence:'A ____ researcher records unexpected results rather than quietly discarding them.',choices:['conscientious','banal','boisterous','callous']},
  clandestine:{sentence:'Investigative journalists uncovered a ____ meeting between the lobbyists and senior officials.',choices:['clandestine','blatant','cogent','commensurate']},
  construe:{sentence:'Courts should not automatically ____ a suspect\'s silence as an admission of guilt.',choices:['construe','avert','cajole','coerce']},
  malleable:{sentence:'Unlike brittle alloys, gold is highly ____ and can be shaped without breaking.',choices:['malleable','affluent','arcane','apprehensive']},
  edify:{sentence:'The documentary aims to ____ viewers by examining the ethical consequences of the policy.',choices:['edify','alienate','admonish','appease']},
  reconcile:{sentence:'Diplomats struggled to ____ the two countries after decades of hostility.',choices:['reconcile','abrogate','ascertain','articulate']}
};
var REMAINING_SENTENCES={
  contemptuous:"The ambassador was openly ____ of the proposal, calling it naive and unworkable.",
  contrite:"The executive issued a ____ apology and accepted full responsibility for the deception.",
  copious:"The investigation produced ____ evidence of systematic accounting fraud.",
  corroborate:"Phone records helped ____ the witness's account of the meeting.",
  credulous:"____ investors accepted the fraudulent returns without examining the underlying assets.",
  culpable:"The inquiry found senior managers ____ for ignoring repeated safety warnings.",
  debase:"Flooding the market with counterfeit currency could ____ the value of the legal tender.",
  debilitate:"The prolonged illness can ____ patients for months after the initial infection.",
  deference:"Junior officials traditionally show considerable ____ to the cabinet secretary.",
  delineate:"The negotiators must ____ the responsibilities of each participating nation.",
  demure:"Her ____ manner concealed a fierce determination to challenge the party leadership.",
  denigrate:"Opponents tried to ____ the scientist rather than address her evidence.",
  deplore:"Human-rights groups ____ the government's use of indefinite detention.",
  depravity:"The court heard disturbing testimony about the ____ of the criminal network.",
  decry:"Community leaders ____ the decision to close the region's only hospital.",
  despondent:"After another rejection, the job seeker became increasingly ____.",
  dexterous:"The surgeon's ____ hands allowed her to complete the delicate procedure.",
  didactic:"The novel is engaging without becoming overly ____ or moralistic.",
  diffident:"Though highly qualified, he remained too ____ to speak during the meeting.",
  dilapidated:"The charity converted a ____ warehouse into temporary housing.",
  diligent:"The auditor's ____ examination uncovered discrepancies others had missed.",
  discerning:"____ consumers questioned whether the luxury label justified the higher price.",
  disconcert:"The moderator's unexpected question appeared to ____ the candidate, who paused visibly and struggled to regain his composure.",
  discredit:"The fabricated photograph was intended to ____ the opposition candidate.",
  disdain:"Many veteran diplomats ____ the use of personal insults in negotiations.",
  disseminate:"The agency used local radio to ____ accurate information during the outbreak.",
  dogmatic:"His ____ refusal to consider contrary evidence stalled the inquiry.",
  dubious:"The committee rejected the contractor's ____ claim for additional expenses.",
  ebullient:"Supporters were ____ after the unexpected election victory.",
  eclectic:"The exhibition presents an ____ mixture of classical and contemporary art.",
  efficacy:"Researchers questioned the ____ of the treatment in elderly patients.",
  egregious:"The regulator imposed a record fine for the bank's ____ misconduct.",
  elusive:"A lasting settlement remained ____ despite months of negotiations.",
  embellish:"The witness admitted that he had begun to ____ his account for dramatic effect.",
  empirical:"The theory is appealing, but it lacks ____ support from controlled studies.",
  encroach:"New housing developments continue to ____ on protected wetlands.",
  endemic:"Corruption had become ____ within several branches of the administration.",
  enervate:"Years of political uncertainty can ____ even the most committed reformers.",
  enfranchise:"The amendment sought to ____ citizens who had long been denied the vote.",
  enigmatic:"The artist remained ____ and rarely explained the meaning of her work.",
  enmity:"The peace agreement ended decades of ____ between the rival communities.",
  entrench:"Subsidies may ____ inefficient practices that would otherwise disappear.",
  erratic:"The pilot was suspended after displaying ____ behavior during several flights.",
  eradicate:"Health officials launched a campaign to ____ the disease from the region.",
  esoteric:"The lecture was so ____ that few students could follow the argument.",
  euphemism:"The phrase 'collateral damage' is often criticized as a ____ for civilian deaths.",
  evince:"Her detailed questions ____ a genuine interest in constitutional law.",
  exasperate:"Repeated delays continued to ____ commuters who relied on the service.",
  exculpate:"New DNA evidence may ____ the prisoner after two decades in custody.",
  exorbitant:"Residents protested the ____ fees charged by the private utility.",
  expedite:"The government created a special office to ____ disaster-relief payments.",
  extol:"Campaign advertisements ____ the candidate's achievements while ignoring his failures.",
  extraneous:"The editor removed ____ details that distracted from the central argument.",
  fallacious:"The policy rests on the ____ assumption that poverty reflects laziness.",
  fervent:"She remained a ____ advocate of press freedom throughout her career.",
  flagrant:"Observers documented a ____ violation of international election law.",
  flippant:"His ____ response to the tragedy provoked widespread outrage.",
  fortuitous:"A ____ encounter with a former colleague led to the breakthrough.",
  fractious:"The prime minister struggled to unite a ____ governing coalition.",
  furtive:"The employee's ____ attempts to copy confidential files raised suspicion.",
  garrulous:"The normally ____ host fell silent when questioned about the missing funds.",
  germane:"The judge ruled that the witness's personal history was not ____ to the case.",
  glib:"The minister's ____ assurances failed to address the complexity of the crisis.",
  gratuitous:"Critics objected to the film's ____ violence, which added nothing to the story.",
  hackneyed:"The speech relied on ____ phrases instead of offering concrete proposals.",
  haphazard:"The relief supplies were distributed in a ____ manner, leaving some villages empty-handed.",
  harangue:"The manager would often ____ employees for minor mistakes in front of customers.",
  heed:"Officials failed to ____ repeated warnings about the unstable bridge.",
  heinous:"The tribunal was established to prosecute the most ____ crimes committed during the war.",
  herald:"The discovery could ____ a new era of personalized medicine.",
  indolent:"The supervisor refused to tolerate ____ employees who avoided difficult assignments.",
  infallible:"No forecasting model is ____, especially during an unprecedented crisis.",
  ingenuous:"His ____ admission of uncertainty made the young researcher seem trustworthy.",
  inhibit:"Fear of retaliation may ____ employees from reporting misconduct.",
  innocuous:"The seemingly ____ software update introduced a serious security flaw.",
  insidious:"The report describes the ____ spread of misinformation through private networks.",
  insolent:"The officer was disciplined for making an ____ remark to her commander.",
  intrepid:"An ____ team of journalists continued reporting from the conflict zone.",
  irascible:"The ____ director was notorious for shouting at staff over minor errors.",
  irrefutable:"Video footage provided ____ evidence that the official had lied.",
  jettison:"The party decided to ____ its unpopular tax proposal before the election.",
  jubilant:"Crowds were ____ when the rescue team emerged with all the missing children.",
  judicious:"A ____ use of public funds can preserve essential services without raising taxes.",
  languid:"Economic activity remained ____ throughout the unusually hot summer.",
  laud:"Environmental groups ____ the court's decision to protect the forest.",
  lethargic:"Demand remained ____ as households postponed major purchases.",
  lucid:"Her ____ explanation made the complex constitutional issue accessible to the public.",
  mercurial:"The CEO's ____ leadership style made long-term planning nearly impossible.",
  malevolent:"Investigators discovered a ____ scheme designed to ruin the whistleblower's career.",
  mendacious:"The newspaper accused the minister of making ____ statements to parliament.",
  morose:"He became increasingly ____ after the project he had led was canceled.",
  mollify:"The company offered refunds in an effort to ____ angry customers.",
  nebulous:"The agreement referred to 'fair access' but left the term deliberately ____.",
  nefarious:"Police uncovered a ____ plot to traffic stolen medical supplies.",
  opulent:"The palace's ____ interior contrasted sharply with the poverty outside its gates.",
  proscribe:"The new regulations ____ the use of certain chemicals near drinking-water sources.",
  oblivious:"The hikers seemed ____ to the storm approaching from the west.",
  obsequious:"His ____ praise of senior officials irritated his more independent colleagues.",
  presumptuous:"It would be ____ to claim that one study has settled the entire debate.",
  ostracize:"Students who challenge the group may be mocked or ____ by their peers.",
  palpable:"A sense of relief was ____ when the ceasefire was announced.",
  ravenous:"After three days without supplies, the stranded climbers were ____.",
  redundant:"Automation made several administrative positions ____.",
  pernicious:"The study examined the ____ effects of chronic discrimination on health.",
  placate:"Officials reduced the proposed fee to ____ small-business owners.",
  reverent:"Visitors maintained a ____ silence inside the ancient memorial.",
  precarious:"Thousands of families remain in a ____ financial position after the factory closure.",
  precipitate:"A sudden withdrawal of credit could ____ a broader banking crisis.",
  preclude:"The absence of reliable records may ____ a definitive conclusion.",
  prodigal:"His ____ spending exhausted the inheritance within a few years.",
  prolific:"The researcher was a ____ author who published more than fifty papers.",
  propensity:"The material has a ____ to crack when exposed to extreme cold.",
  propitiate:"The ruler made concessions to ____ the powerful landowners.",
  quandary:"The court's conflicting precedents left the judge in a difficult ____.",
  quell:"Police used tear gas to ____ the violent disturbance.",
  retribution:"Witnesses feared ____ from members of the criminal organization.",
  reclusive:"The ____ novelist had not given an interview in more than a decade.",
  relinquish:"The president refused to ____ control of the emergency funds.",
  reprehensible:"The committee described the deliberate concealment of abuse as ____.",
  rescind:"The university agreed to ____ the disciplinary order after reviewing new evidence.",
  reticent:"Officials remained ____ about the details of the secret negotiations.",
  sagacious:"The veteran diplomat offered ____ advice that prevented an escalation.",
  sardonic:"Her ____ remark exposed the absurdity of the official explanation.",
  scrupulous:"The laboratory is ____ about documenting every change to its procedures.",
  spurious:"The website spread ____ claims about the safety of vaccines.",
  staunch:"She has remained a ____ defender of judicial independence.",
  sporadic:"____ fighting continued along the border despite the ceasefire.",
  suppress:"The regime attempted to ____ independent reporting on the protests.",
  succinct:"Please provide a ____ summary of the report's main conclusions.",
  superfluous:"The revised form removes several ____ questions.",
  turbulent:"The airline struggled to survive a ____ period of strikes and fuel shortages.",
  unprecedented:"The country experienced an ____ decline in its working-age population.",
  tenacious:"The ____ investigator pursued the case despite political pressure.",
  vicarious:"Readers experience ____ excitement through the explorer's account.",
  tirade:"The mayor launched into a lengthy ____ against the national media.",
  transient:"The increase in prices proved ____ rather than permanent.",
  volatile:"Investors avoided the region because of its ____ political climate.",
  unequivocal:"The court issued an ____ rejection of the government's argument.",
  wane:"Public enthusiasm began to ____ as the project's costs increased.",
  venerate:"Many communities ____ the physician for her decades of service.",
  withstand:"The new bridge was designed to ____ powerful earthquakes.",
  virulent:"The candidate faced a ____ campaign of personal attacks online.",
  vitriolic:"The debate deteriorated into a ____ exchange of accusations.",
  whimsical:"The architect's ____ design features windows shaped like clouds.",
  zealot:"The movement expelled a ____ who advocated violence against opponents.",
  watershed:"The ruling marked a ____ in the struggle for equal rights.",
  yearn:"Many exiles ____ to return to their homeland.",
};
var REVIEWED_CHOICE_OVERRIDES={
  demure:['demure','copious','culpable','dilapidated'],
  diligent:['diligent','blatant','boisterous','callous'],
  discerning:['discerning','bereft','boisterous','dilapidated'],
  enmity:['enmity','brevity','catharsis','efficacy'],
  esoteric:['esoteric','affable','boisterous','diligent'],
  lucid:['lucid','dilapidated','ravenous','turbulent'],
  mendacious:['mendacious','copious','diligent','reverent'],
  prodigal:['prodigal','clandestine','conscientious','dilapidated'],
  sardonic:['sardonic','affluent','diligent','reverent'],
  tenacious:['tenacious','affluent','demure','languid'],
  virulent:['virulent','demure','lucid','reverent'],
  whimsical:['whimsical','culpable','diligent','reverent']
};
function autoChoices(word){
  if(REVIEWED_CHOICE_OVERRIDES[word])return REVIEWED_CHOICE_OVERRIDES[word].slice();
  var words=window.EIKEN_WORDS||[],answer=words.find(function(item){return item.w===word}),answerPos=answer.pos||answer.p,related=[].concat(answer.synonyms||[],answer.antonyms||[]).map(function(value){return String(value).toLowerCase()}),pool=words.filter(function(item){var candidateRelated=[].concat(item.synonyms||[],item.antonyms||[]).map(function(value){return String(value).toLowerCase()});return item.w!==word&&(item.pos||item.p)===answerPos&&related.indexOf(item.w.toLowerCase())<0&&candidateRelated.indexOf(word.toLowerCase())<0});
  var seed=word.split('').reduce(function(total,ch){return total+ch.charCodeAt(0)},0),choices=[word];
  for(var i=0;choices.length<4&&i<pool.length;i++){var candidate=pool[(seed+i)%pool.length].w;if(choices.indexOf(candidate)<0)choices.push(candidate)}
  return choices;
}
Object.keys(REMAINING_SENTENCES).forEach(function(word){OVERRIDES[word]={sentence:REMAINING_SENTENCES[word],choices:autoChoices(word)}});
Object.assign(OVERRIDES,window.EIKEN_VOCAB_EXPANSION_QUESTIONS||{});
OVERRIDES.intransigent={sentence:'Even after the audit exposed serious flaws, the minister remained ____ and refused to revise the policy.',choices:['intransigent','equivocal','magnanimous','sanguine']};
OVERRIDES.indispensable={sentence:'Independent courts are ____ to a democracy seeking to protect citizens from arbitrary rule.',choices:['indispensable','intransigent','inadvertent','unprecedented']};
OVERRIDES.impede={sentence:'Lengthy approval procedures could ____ the delivery of emergency supplies to isolated communities.',choices:['impede','engender','curtail','rectify']};
OVERRIDES.perpetuate={sentence:'Ignoring unequal access to education may ____ the economic divisions the reform was intended to eliminate.',choices:['perpetuate','obfuscate','substantiate','relegate']};
OVERRIDES.redundant={sentence:'After the software was introduced, several administrative positions became ____ and were eliminated.',choices:['redundant','succinct','turbulent','unprecedented']};
OVERRIDES.superfluous={sentence:'After the editor condensed the report, several ____ paragraphs that merely repeated earlier arguments were removed.',choices:['superfluous','vociferous','contentious','conspicuous']};
window.EIKEN_QUIZ_ITEMS=(window.EIKEN_WORDS||[]).filter(function(word){return OVERRIDES[word.w]||word.s}).map(function(word){var override=OVERRIDES[word.w];return{id:word.w+'-001',word:word.w,sentence:override?override.sentence:word.s,choices:override?override.choices:autoChoices(word.w),source:override?'manual-review':'curated-v1'}});
var qualityApi=window.EIKEN_QUIZ_QUALITY;
if(qualityApi)window.EIKEN_QUIZ_ITEMS.forEach(function(item){item.quality=qualityApi.scoreItem(item,window.EIKEN_WORDS||[],window.EIKEN_QUIZ_ITEMS);item.difficulty=qualityApi.difficultyIndex(item.quality)});
window.EIKEN_EXAMPLE_LIBRARY=window.EIKEN_QUIZ_ITEMS.filter(function(item){return!qualityApi||item.quality.passed}).map(function(item){return{id:item.id,word:item.word,sentence:item.sentence,choices:item.choices.slice(),source:item.source,quality:item.quality,difficulty:item.difficulty,approved:true}});
var approvedExamples={};
window.EIKEN_EXAMPLE_LIBRARY.forEach(function(item){approvedExamples[item.word]=item.sentence});
(window.EIKEN_WORDS||[]).forEach(function(word){if(approvedExamples[word.w])word.s=approvedExamples[word.w]});
window.EIKEN_REJECTED_QUIZ_WORDS=(window.EIKEN_WORDS||[]).filter(function(word){return!word.s&&!OVERRIDES[word.w]}).map(function(word){return word.w});
})();
