(function(){
'use strict';
var GENERIC_TEMPLATES={
  'The new policy could ____ efforts to restore public trust.':true,
  'Independent investigators tried to ____ the claim before the report was released.':true,
  'Critics warned that officials might ____ the principles they had promised to uphold.':true,
  "Experts described the government's response as ____ during the national debate.":true,
  'The committee rejected what it considered an ____ approach to the problem.':true,
  'Her ____ explanation changed how the public understood the controversy.':true,
  'The report identified ____ as a serious obstacle to lasting reform.':true,
  'Public concern about ____ grew after the investigation.':true,
  'The debate highlighted the social consequences of ____.':true
};
var OVERRIDES={
  abdicate:{sentence:'The board accused the CEO of trying to ____ responsibility for the failed merger.',choices:['abdicate','ascertain','articulate','appease']},
  abhor:{sentence:'Many citizens ____ the use of torture under any circumstances.',choices:['abhor','appease','amalgamate','admonish']},
  abject:{sentence:'The displaced families were living in ____ poverty after the conflict.',choices:['abject','affluent','arcane','adroit']},
  abrogate:{sentence:'The new administration threatened to ____ the treaty without consulting its allies.',choices:['abrogate','amalgamate','articulate','ascertain']},
  accolade:{sentence:'For the young scientist, the international prize was the highest ____ of her career.',choices:['accolade','alacrity','animosity','anachronism']},
  acquiesce:{sentence:'After months of resistance, the board finally agreed to ____ to the shareholders\' demands.',choices:['acquiesce','appease','articulate','ascertain']},
  admonish:{sentence:'The judge had to ____ the attorney for repeatedly interrupting the witness.',choices:['admonish','abhor','aggrandize','alienate']},
  adroit:{sentence:'Her ____ handling of the negotiations prevented a costly strike.',choices:['adroit','affable','ambivalent','arduous']},
  affable:{sentence:'Despite his senior position, the professor remained ____ and easy to approach.',choices:['affable','arcane','apprehensive','abject']},
  affluent:{sentence:'The tax incentive disproportionately benefited ____ households in the capital.',choices:['affluent','abject','arduous','ambivalent']},
  aggrandize:{sentence:'Critics accused the leader of using the emergency to ____ his own power.',choices:['aggrandize','abdicate','abrogate','amalgamate']},
  alacrity:{sentence:'She accepted the difficult overseas assignment with surprising ____.',choices:['alacrity','accolade','animosity','antipathy']},
  alienate:{sentence:'The candidate\'s harsh rhetoric may ____ moderate voters.',choices:['alienate','appease','admonish','articulate']},
  amalgamate:{sentence:'The proposal would ____ the two regional agencies into a single authority.',choices:['amalgamate','alienate','appease','aggrandize']},
  ambivalent:{sentence:'Seeing both compelling benefits and serious risks, voters remained ____ about the proposal.',choices:['ambivalent','affable','adroit','arcane']},
  amenable:{sentence:'The committee proved ____ to revising the regulations after hearing expert testimony.',choices:['amenable','affluent','arduous','abject']},
  anachronism:{sentence:'In an era of instant digital communication, the fax machine can seem like an ____.',choices:['anachronism','accolade','alacrity','animosity']},
  animosity:{sentence:'Years of territorial disputes fueled deep ____ between the neighboring states.',choices:['animosity','accolade','alacrity','anachronism']},
  antipathy:{sentence:'The journalist made no attempt to conceal her ____ toward political corruption.',choices:['antipathy','accolade','alacrity','anachronism']},
  appease:{sentence:'The government offered limited concessions to ____ the angry protesters.',choices:['appease','admonish','articulate','ascertain']},
  apprehensive:{sentence:'Investors were ____ about entering a market with such unstable regulations.',choices:['apprehensive','affable','adroit','affluent']},
  arcane:{sentence:'Only a handful of specialists understood the ____ provisions of the tax code.',choices:['arcane','affable','affluent','ambivalent']},
  arduous:{sentence:'Restoring the polluted wetland proved to be an ____ task.',choices:['arduous','affable','affluent','ambivalent']},
  articulate:{sentence:'Each candidate must ____ a coherent plan for reducing public debt.',choices:['articulate','ascertain','appease','amalgamate']},
  ascertain:{sentence:'Investigators worked to ____ whether the safety records had been falsified.',choices:['ascertain','admonish','alienate','appease']},
  astute:{sentence:'Her ____ analysis identified a risk that the other advisers had overlooked.',choices:['astute','banal','boisterous','callous']},
  atrophy:{sentence:'Without regular exercise, the muscles surrounding the injured joint may begin to ____.',choices:['atrophy','avert','cajole','coerce']},
  avarice:{sentence:'The novel portrays a banker whose ____ ultimately destroys his family and reputation.',choices:['avarice','brevity','camaraderie','catharsis']},
  avert:{sentence:'Prompt diplomatic intervention helped ____ a wider regional conflict.',choices:['avert','atrophy','cajole','coerce']},
  banal:{sentence:'The critic dismissed the speech as a collection of ____ observations and tired slogans.',choices:['banal','astute','boisterous','circumspect']},
  belie:{sentence:'The official statistics ____ claims that the economic recovery has benefited everyone.',choices:['belie','cajole','coalesce','construe']},
  bereft:{sentence:'Without independent oversight, the agency was ____ of meaningful accountability.',choices:['bereft','blatant','cogent','conciliatory']},
  blatant:{sentence:'The altered records were a ____ attempt to conceal the company\'s safety violations.',choices:['blatant','circumspect','conscientious','conciliatory']},
  boisterous:{sentence:'The teacher struggled to quiet the ____ crowd gathered outside the auditorium.',choices:['boisterous','banal','bereft','cogent']},
  brevity:{sentence:'Given the limited time, the chair praised the speaker for her ____.',choices:['brevity','avarice','camaraderie','complicity']},
  cajole:{sentence:'Lobbyists tried to ____ undecided lawmakers into supporting the controversial bill.',choices:['cajole','avert','atrophy','coalesce']},
  callous:{sentence:'The company was condemned for its ____ disregard for the welfare of displaced residents.',choices:['callous','astute','commensurate','conscientious']},
  camaraderie:{sentence:'Months of working under difficult conditions fostered strong ____ among the volunteers.',choices:['camaraderie','avarice','brevity','complicity']},
  catharsis:{sentence:'For many survivors, giving public testimony provided a sense of ____.',choices:['catharsis','avarice','brevity','conflagration']},
  circumspect:{sentence:'Diplomats remained ____ in their public comments while negotiations were still under way.',choices:['circumspect','blatant','boisterous','callous']},
  coalesce:{sentence:'Several small opposition groups began to ____ around a single reform candidate.',choices:['coalesce','avert','cajole','coerce']},
  coerce:{sentence:'The law prohibits employers from attempting to ____ workers into unpaid overtime.',choices:['coerce','avert','atrophy','coalesce']},
  cogent:{sentence:'The attorney presented a ____ argument supported by extensive documentary evidence.',choices:['cogent','banal','boisterous','callous']},
  commensurate:{sentence:'The penalty should be ____ with the seriousness of the offense.',choices:['commensurate','banal','bereft','clandestine']},
  complicity:{sentence:'Newly released documents revealed the official\'s ____ in the corruption scheme.',choices:['complicity','brevity','camaraderie','catharsis']},
  conciliatory:{sentence:'Hoping to reopen negotiations, the minister adopted a more ____ tone.',choices:['conciliatory','blatant','callous','clandestine']},
  conflagration:{sentence:'Firefighters from three provinces struggled to contain the massive ____.',choices:['conflagration','avarice','brevity','complicity']},
  conscientious:{sentence:'A ____ researcher records unexpected results rather than quietly discarding them.',choices:['conscientious','banal','boisterous','callous']},
  clandestine:{sentence:'Investigative journalists uncovered a ____ meeting between the lobbyists and senior officials.',choices:['clandestine','blatant','cogent','commensurate']},
  construe:{sentence:'Courts should not automatically ____ a suspect\'s silence as an admission of guilt.',choices:['construe','avert','cajole','coerce']},
  malleable:{sentence:'Unlike brittle alloys, gold is highly ____ and can be shaped without breaking.',choices:['malleable','affluent','arcane','apprehensive']},
  edify:{sentence:'The documentary aims to ____ viewers by examining the ethical consequences of the policy.',choices:['edify','alienate','admonish','appease']},
  reconcile:{sentence:'Diplomats struggled to ____ the two countries after decades of hostility.',choices:['reconcile','abrogate','ascertain','articulate']}
};
var REMAINING_SENTENCES={
  contemptuous:"The ambassador was openly ____ of the proposal, calling it naive and unworkable.",
  contrite:"The executive issued a ____ apology and accepted full responsibility for the deception.",
  copious:"The investigation produced ____ evidence of systematic accounting fraud.",
  corroborate:"Phone records helped ____ the witness's account of the meeting.",
  credulous:"____ investors accepted the fraudulent returns without examining the underlying assets.",
  culpable:"The inquiry found senior managers ____ for ignoring repeated safety warnings.",
  debase:"Flooding the market with counterfeit currency could ____ the value of the legal tender.",
  debilitate:"The prolonged illness can ____ patients for months after the initial infection.",
  deference:"Junior officials traditionally show considerable ____ to the cabinet secretary.",
  delineate:"The negotiators must ____ the responsibilities of each participating nation.",
  demure:"Her ____ manner concealed a fierce determination to challenge the party leadership.",
  denigrate:"Opponents tried to ____ the scientist rather than address her evidence.",
  deplore:"Human-rights groups ____ the government's use of indefinite detention.",
  depravity:"The court heard disturbing testimony about the ____ of the criminal network.",
  decry:"Community leaders ____ the decision to close the region's only hospital.",
  despondent:"After another rejection, the job seeker became increasingly ____.",
  dexterous:"The surgeon's ____ hands allowed her to complete the delicate procedure.",
  didactic:"The novel is engaging without becoming overly ____ or moralistic.",
  diffident:"Though highly qualified, he remained too ____ to speak during the meeting.",
  dilapidated:"The charity converted a ____ warehouse into temporary housing.",
  diligent:"The auditor's ____ examination uncovered discrepancies others had missed.",
  discerning:"____ consumers questioned whether the luxury label justified the higher price.",
  disconcert:"The moderator's unexpected question appeared to ____ the candidate, who paused visibly and struggled to regain his composure.",
  discredit:"The fabricated photograph was intended to ____ the opposition candidate.",
  disdain:"Many veteran diplomats ____ the use of personal insults in negotiations.",
  disseminate:"The agency used local radio to ____ accurate information during the outbreak.",
  dogmatic:"His ____ refusal to consider contrary evidence stalled the inquiry.",
  dubious:"The committee rejected the contractor's ____ claim for additional expenses.",
  ebullient:"Supporters were ____ after the unexpected election victory.",
  eclectic:"The exhibition presents an ____ mixture of classical and contemporary art.",
  efficacy:"Researchers questioned the ____ of the treatment in elderly patients.",
  egregious:"The regulator imposed a record fine for the bank's ____ misconduct.",
  elusive:"A lasting settlement remained ____ despite months of negotiations.",
  embellish:"The witness admitted that he had begun to ____ his account for dramatic effect.",
  empirical:"The theory is appealing, but it lacks ____ support from controlled studies.",
  encroach:"New housing developments continue to ____ on protected wetlands.",
  endemic:"Corruption had become ____ within several branches of the administration.",
  enervate:"Years of political uncertainty can ____ even the most committed reformers.",
  enfranchise:"The amendment sought to ____ citizens who had long been denied the vote.",
  enigmatic:"The artist remained ____ and rarely explained the meaning of her work.",
  enmity:"The peace agreement ended decades of ____ between the rival communities.",
  entrench:"Subsidies may ____ inefficient practices that would otherwise disappear.",
  erratic:"The pilot was suspended after displaying ____ behavior during several flights.",
  eradicate:"Health officials launched a campaign to ____ the disease from the region.",
  esoteric:"The lecture was so ____ that few students could follow the argument.",
  euphemism:"The phrase 'collateral damage' is often criticized as a ____ for civilian deaths.",
  evince:"Her detailed questions ____ a genuine interest in constitutional law.",
  exasperate:"Repeated delays continued to ____ commuters who relied on the service.",
  exculpate:"New DNA evidence may ____ the prisoner after two decades in custody.",
  exorbitant:"Residents protested the ____ fees charged by the private utility.",
  expedite:"The government created a special office to ____ disaster-relief payments.",
  extol:"Campaign advertisements ____ the candidate's achievements while ignoring his failures.",
  extraneous:"The editor removed ____ details that distracted from the central argument.",
  fallacious:"The policy rests on the ____ assumption that poverty reflects laziness.",
  fervent:"She remained a ____ advocate of press freedom throughout her career.",
  flagrant:"Observers documented a ____ violation of international election law.",
  flippant:"His ____ response to the tragedy provoked widespread outrage.",
  fortuitous:"A ____ encounter with a former colleague led to the breakthrough.",
  fractious:"The prime minister struggled to unite a ____ governing coalition.",
  furtive:"The employee's ____ attempts to copy confidential files raised suspicion.",
  garrulous:"The normally ____ host fell silent when questioned about the missing funds.",
  germane:"The judge ruled that the witness's personal history was not ____ to the case.",
  glib:"The minister's ____ assurances failed to address the complexity of the crisis.",
  gratuitous:"Critics objected to the film's ____ violence, which added nothing to the story.",
  hackneyed:"The speech relied on ____ phrases instead of offering concrete proposals.",
  haphazard:"The relief supplies were distributed in a ____ manner, leaving some villages empty-handed.",
  harangue:"The manager would often ____ employees for minor mistakes in front of customers.",
  heed:"Officials failed to ____ repeated warnings about the unstable bridge.",
  heinous:"The tribunal was established to prosecute the most ____ crimes committed during the war.",
  herald:"The discovery could ____ a new era of personalized medicine.",
  indolent:"The supervisor refused to tolerate ____ employees who avoided difficult assignments.",
  infallible:"No forecasting model is ____, especially during an unprecedented crisis.",
  ingenuous:"His ____ admission of uncertainty made the young researcher seem trustworthy.",
  inhibit:"Fear of retaliation may ____ employees from reporting misconduct.",
  innocuous:"The seemingly ____ software update introduced a serious security flaw.",
  insidious:"The report describes the ____ spread of misinformation through private networks.",
  insolent:"The officer was disciplined for making an ____ remark to her commander.",
  intrepid:"An ____ team of journalists continued reporting from the conflict zone.",
  irascible:"The ____ director was notorious for shouting at staff over minor errors.",
  irrefutable:"Video footage provided ____ evidence that the official had lied.",
  jettison:"The party decided to ____ its unpopular tax proposal before the election.",
  jubilant:"Crowds were ____ when the rescue team emerged with all the missing children.",
  judicious:"A ____ use of public funds can preserve essential services without raising taxes.",
  languid:"Economic activity remained ____ throughout the unusually hot summer.",
  laud:"Environmental groups ____ the court's decision to protect the forest.",
  lethargic:"Demand remained ____ as households postponed major purchases.",
  lucid:"Her ____ explanation made the complex constitutional issue accessible to the public.",
  mercurial:"The CEO's ____ leadership style made long-term planning nearly impossible.",
  malevolent:"Investigators discovered a ____ scheme designed to ruin the whistleblower's career.",
  mendacious:"The newspaper accused the minister of making ____ statements to parliament.",
  morose:"He became increasingly ____ after the project he had led was canceled.",
  mollify:"The company offered refunds in an effort to ____ angry customers.",
  nebulous:"The agreement referred to 'fair access' but left the term deliberately ____.",
  nefarious:"Police uncovered a ____ plot to traffic stolen medical supplies.",
  opulent:"The palace's ____ interior contrasted sharply with the poverty outside its gates.",
  proscribe:"The new regulations ____ the use of certain chemicals near drinking-water sources.",
  oblivious:"The hikers seemed ____ to the storm approaching from the west.",
  obsequious:"His ____ praise of senior officials irritated his more independent colleagues.",
  presumptuous:"It would be ____ to claim that one study has settled the entire debate.",
  ostracize:"Students who challenge the group may be mocked or ____ by their peers.",
  palpable:"A sense of relief was ____ when the ceasefire was announced.",
  ravenous:"After three days without supplies, the stranded climbers were ____.",
  redundant:"Automation made several administrative positions ____.",
  pernicious:"The study examined the ____ effects of chronic discrimination on health.",
  placate:"Officials reduced the proposed fee to ____ small-business owners.",
  reverent:"Visitors maintained a ____ silence inside the ancient memorial.",
  precarious:"Thousands of families remain in a ____ financial position after the factory closure.",
  precipitate:"A sudden withdrawal of credit could ____ a broader banking crisis.",
  preclude:"The absence of reliable records may ____ a definitive conclusion.",
  prodigal:"His ____ spending exhausted the inheritance within a few years.",
  prolific:"The researcher was a ____ author who published more than fifty papers.",
  propensity:"The material has a ____ to crack when exposed to extreme cold.",
  propitiate:"The ruler made concessions to ____ the powerful landowners.",
  quandary:"The court's conflicting precedents left the judge in a difficult ____.",
  quell:"Police used tear gas to ____ the violent disturbance.",
  retribution:"Witnesses feared ____ from members of the criminal organization.",
  reclusive:"The ____ novelist had not given an interview in more than a decade.",
  relinquish:"The president refused to ____ control of the emergency funds.",
  reprehensible:"The committee described the deliberate concealment of abuse as ____.",
  rescind:"The university agreed to ____ the disciplinary order after reviewing new evidence.",
  reticent:"Officials remained ____ about the details of the secret negotiations.",
  sagacious:"The veteran diplomat offered ____ advice that prevented an escalation.",
  sardonic:"Her ____ remark exposed the absurdity of the official explanation.",
  scrupulous:"The laboratory is ____ about documenting every change to its procedures.",
  spurious:"The website spread ____ claims about the safety of vaccines.",
  staunch:"She has remained a ____ defender of judicial independence.",
  sporadic:"____ fighting continued along the border despite the ceasefire.",
  suppress:"The regime attempted to ____ independent reporting on the protests.",
  succinct:"Please provide a ____ summary of the report's main conclusions.",
  superfluous:"The revised form removes several ____ questions.",
  turbulent:"The airline struggled to survive a ____ period of strikes and fuel shortages.",
  unprecedented:"The country experienced an ____ decline in its working-age population.",
  tenacious:"The ____ investigator pursued the case despite political pressure.",
  vicarious:"Readers experience ____ excitement through the explorer's account.",
  tirade:"The mayor launched into a lengthy ____ against the national media.",
  transient:"The increase in prices proved ____ rather than permanent.",
  volatile:"Investors avoided the region because of its ____ political climate.",
  unequivocal:"The court issued an ____ rejection of the government's argument.",
  wane:"Public enthusiasm began to ____ as the project's costs increased.",
  venerate:"Many communities ____ the physician for her decades of service.",
  withstand:"The new bridge was designed to ____ powerful earthquakes.",
  virulent:"The candidate faced a ____ campaign of personal attacks online.",
  vitriolic:"The debate deteriorated into a ____ exchange of accusations.",
  whimsical:"The architect's ____ design features windows shaped like clouds.",
  zealot:"The movement expelled a ____ who advocated violence against opponents.",
  watershed:"The ruling marked a ____ in the struggle for equal rights.",
  yearn:"Many exiles ____ to return to their homeland.",
};
var REVIEWED_CHOICE_OVERRIDES={
  demure:['demure','copious','culpable','dilapidated'],
  diligent:['diligent','blatant','boisterous','callous'],
  discerning:['discerning','bereft','boisterous','dilapidated'],
  enmity:['enmity','brevity','catharsis','efficacy'],
  esoteric:['esoteric','affable','boisterous','diligent'],
  lucid:['lucid','dilapidated','ravenous','turbulent'],
  mendacious:['mendacious','copious','diligent','reverent'],
  prodigal:['prodigal','clandestine','conscientious','dilapidated'],
  sardonic:['sardonic','affluent','diligent','reverent'],
  tenacious:['tenacious','affluent','demure','languid'],
  virulent:['virulent','demure','lucid','reverent'],
  whimsical:['whimsical','culpable','diligent','reverent']
};
function autoChoices(word){
  if(REVIEWED_CHOICE_OVERRIDES[word])return REVIEWED_CHOICE_OVERRIDES[word].slice();
  var words=window.EIKEN_WORDS||[],answer=words.find(function(item){return item.w===word}),answerPos=answer.pos||answer.p,related=[].concat(answer.synonyms||[],answer.antonyms||[]).map(function(value){return String(value).toLowerCase()}),pool=words.filter(function(item){var candidateRelated=[].concat(item.synonyms||[],item.antonyms||[]).map(function(value){return String(value).toLowerCase()});return item.w!==word&&(item.pos||item.p)===answerPos&&related.indexOf(item.w.toLowerCase())<0&&candidateRelated.indexOf(word.toLowerCase())<0});
  var seed=word.split('').reduce(function(total,ch){return total+ch.charCodeAt(0)},0),choices=[word];
  for(var i=0;choices.length<4&&i<pool.length;i++){var candidate=pool[(seed+i)%pool.length].w;if(choices.indexOf(candidate)<0)choices.push(candidate)}
  return choices;
}
Object.keys(REMAINING_SENTENCES).forEach(function(word){OVERRIDES[word]={sentence:REMAINING_SENTENCES[word],choices:autoChoices(word)}});
OVERRIDES.intransigent={sentence:'Even after the audit exposed serious flaws, the minister remained ____ and refused to revise the policy.',choices:['intransigent','equivocal','magnanimous','sanguine']};
OVERRIDES.indispensable={sentence:'Independent courts are ____ to a democracy seeking to protect citizens from arbitrary rule.',choices:['indispensable','intransigent','inadvertent','unprecedented']};
OVERRIDES.impede={sentence:'Lengthy approval procedures could ____ the delivery of emergency supplies to isolated communities.',choices:['impede','engender','curtail','rectify']};
OVERRIDES.perpetuate={sentence:'Ignoring unequal access to education may ____ the economic divisions the reform was intended to eliminate.',choices:['perpetuate','obfuscate','substantiate','relegate']};
OVERRIDES.superfluous={sentence:'After the editor condensed the report, several ____ paragraphs that merely repeated earlier arguments were removed.',choices:['superfluous','vociferous','contentious','conspicuous']};
window.EIKEN_QUIZ_ITEMS=(window.EIKEN_WORDS||[]).filter(function(word){return OVERRIDES[word.w]||!GENERIC_TEMPLATES[word.s]}).map(function(word){var override=OVERRIDES[word.w];return{id:word.w+'-001',word:word.w,sentence:override?override.sentence:word.s,choices:override?override.choices:autoChoices(word.w),source:override?'manual-review':'curated-v1'}});
var qualityApi=window.EIKEN_QUIZ_QUALITY;
if(qualityApi)window.EIKEN_QUIZ_ITEMS.forEach(function(item){item.quality=qualityApi.scoreItem(item,window.EIKEN_WORDS||[],window.EIKEN_QUIZ_ITEMS);item.difficulty=qualityApi.difficultyIndex(item.quality)});
window.EIKEN_EXAMPLE_LIBRARY=window.EIKEN_QUIZ_ITEMS.filter(function(item){return!qualityApi||item.quality.passed}).map(function(item){return{id:item.id,word:item.word,sentence:item.sentence,choices:item.choices.slice(),source:item.source,quality:item.quality,difficulty:item.difficulty,approved:true}});
window.EIKEN_REJECTED_QUIZ_WORDS=(window.EIKEN_WORDS||[]).filter(function(word){return GENERIC_TEMPLATES[word.s]&&!OVERRIDES[word.w]}).map(function(word){return word.w});
})();
