(function(){
'use strict';
var DETAILS={
  abate:{pos:"verb",synonyms:["subside","diminish"],antonyms:["intensify","increase"],collocations:["the storm abated","show no sign of abating"]},
  abdicate:{pos:"verb",synonyms:["renounce","abandon"],antonyms:["明確な反意語なし"],collocations:["policy could abdicate efforts to","The new policy could abdicate efforts to restore public"]},
  aberration:{pos:"noun",synonyms:["anomaly","deviation"],antonyms:["normality","conformity"],collocations:["an aberration from the norm","a temporary aberration"]},
  abhor:{pos:"verb",synonyms:["loathe","execrate"],antonyms:["明確な反意語なし"],collocations:["tried to abhor the claim","Independent investigators tried to abhor the claim before the"]},
  abject:{pos:"adjective",synonyms:["miserable","hopeless"],antonyms:["明確な反意語なし"],collocations:["Her abject explanation changed","Her abject explanation changed how the"]},
  abrogate:{pos:"verb",synonyms:["revoke","repeal"],antonyms:["明確な反意語なし"],collocations:["policy could abrogate efforts to","The new policy could abrogate efforts to restore public"]},
  accolade:{pos:"noun",synonyms:["honor","award"],antonyms:["明確な反意語なし"],collocations:["concern about accolade grew after","Public concern about accolade grew after the investigation"]},
  acquiesce:{pos:"verb",synonyms:["comply","assent"],antonyms:["dissent"],collocations:["officials might acquiesce the principles","warned that officials might acquiesce the principles they had"]},
  acrimonious:{pos:"adjective",synonyms:["bitter","hostile"],antonyms:["amicable","cordial"],collocations:["an acrimonious dispute","an acrimonious divorce"]},
  admonish:{pos:"verb",synonyms:["reprove","discourage"],antonyms:["明確な反意語なし"],collocations:["policy could admonish efforts to","The new policy could admonish efforts to restore public"]},
  adroit:{pos:"adjective",synonyms:["dextrous","dexterous"],antonyms:["maladroit"],collocations:["considered an adroit approach to","what it considered an adroit approach to the problem"]},
  adversity:{pos:"unknown",synonyms:["hardship","hostility"],antonyms:["明確な反意語なし"],collocations:["face of adversity","in the face of adversity"]},
  affable:{pos:"adjective",synonyms:["friendly","genial"],antonyms:["明確な反意語なし"],collocations:["Her affable explanation changed","Her affable explanation changed how the"]},
  affluent:{pos:"adjective",synonyms:["wealthy","rich"],antonyms:["明確な反意語なし"],collocations:["response as affluent during the","the government's response as affluent during the national debate"]},
  aggrandize:{pos:"verb",synonyms:["dramatise","embellish"],antonyms:["明確な反意語なし"],collocations:["tried to aggrandize the claim","Independent investigators tried to aggrandize the claim before the"]},
  alacrity:{pos:"noun",synonyms:["briskness","enthusiasm"],antonyms:["明確な反意語なし"],collocations:["consequences of alacrity","the social consequences of alacrity"]},
  alienate:{pos:"verb",synonyms:["estrange","disaffect"],antonyms:["明確な反意語なし"],collocations:["policy could alienate efforts to","The new policy could alienate efforts to restore public"]},
  alleviate:{pos:"unknown",synonyms:["relieve","assuage"],antonyms:["明確な反意語なし"],collocations:["intended to alleviate the burden","subsidy is intended to alleviate the burden on low-income"]},
  amalgamate:{pos:"verb",synonyms:["unify","consolidated"],antonyms:["明確な反意語なし"],collocations:["tried to amalgamate the claim","Independent investigators tried to amalgamate the claim before the"]},
  ambiguous:{pos:"unknown",synonyms:["equivocal","enigmatic"],antonyms:["unequivocal","univocal"],collocations:["contract contained ambiguous language that","The contract contained ambiguous language that led to"]},
  ambivalent:{pos:"adjective",synonyms:["equivocal","ambiguous"],antonyms:["明確な反意語なし"],collocations:["Her ambivalent explanation changed","Her ambivalent explanation changed how the"]},
  amenable:{pos:"adjective",synonyms:["compliant","tractable"],antonyms:["unamenable"],collocations:["response as amenable during the","the government's response as amenable during the national debate"]},
  amnesty:{pos:"noun",synonyms:["pardon","free pardon"],antonyms:["明確な反意語なし"],collocations:["announced an amnesty for minor","The government announced an amnesty for minor tax violations"]},
  anachronism:{pos:"noun",synonyms:["mistiming","misdating"],antonyms:["明確な反意語なし"],collocations:["concern about anachronism grew after","Public concern about anachronism grew after the investigation"]},
  animosity:{pos:"noun",synonyms:["bad blood","animus"],antonyms:["明確な反意語なし"],collocations:["consequences of animosity","the social consequences of animosity"]},
  anomaly:{pos:"noun",synonyms:["abnormality","deviance"],antonyms:["明確な反意語なし"],collocations:["found an anomaly in the","Researchers found an anomaly in the data that"]},
  antipathy:{pos:"noun",synonyms:["aversion","distaste"],antonyms:["明確な反意語なし"],collocations:["report identified antipathy as a","The report identified antipathy as a serious obstacle"]},
  appease:{pos:"verb",synonyms:["placate","lenify"],antonyms:["明確な反意語なし"],collocations:["tried to appease the claim","Independent investigators tried to appease the claim before the"]},
  apprehensive:{pos:"adjective",synonyms:["anxious","afraid"],antonyms:["明確な反意語なし"],collocations:["Her apprehensive explanation changed","Her apprehensive explanation changed how the"]},
  arbitrary:{pos:"noun",synonyms:["discretionary","discretional"],antonyms:["nonarbitrary","unarbitrary"],collocations:["restrictions were arbitrary and unfair","that the restrictions were arbitrary and unfair"]},
  arcane:{pos:"adjective",synonyms:["esoteric","cryptic"],antonyms:["明確な反意語なし"],collocations:["response as arcane during the","the government's response as arcane during the national debate"]},
  arduous:{pos:"adjective",synonyms:["laborious","toilsome"],antonyms:["明確な反意語なし"],collocations:["considered an arduous approach to","what it considered an arduous approach to the problem"]},
  articulate:{pos:"verb",synonyms:["well-spoken","eloquent"],antonyms:["inarticulate","unarticulate"],collocations:["officials might articulate the principles","warned that officials might articulate the principles they had"]},
  ascertain:{pos:"verb",synonyms:["see to it","see"],antonyms:["明確な反意語なし"],collocations:["policy could ascertain efforts to","The new policy could ascertain efforts to restore public"]},
  assuage:{pos:"verb",synonyms:["alleviate","ease"],antonyms:["aggravate","intensify"],collocations:["assuage fears","assuage concerns"]},
  astute:{pos:"adjective",synonyms:["shrewd","smart"],antonyms:["明確な反意語なし"],collocations:["considered an astute approach to","what it considered an astute approach to the problem"]},
  atrophy:{pos:"verb",synonyms:["wasting","withering"],antonyms:["明確な反意語なし"],collocations:["officials might atrophy the principles","warned that officials might atrophy the principles they had"]},
  austere:{pos:"adjective",synonyms:["forbidding","stern"],antonyms:["extravagant","flamboyant"],collocations:["reflects an austere approach to","new budget reflects an austere approach to government spending"]},
  avarice:{pos:"noun",synonyms:["cupidity","greed"],antonyms:["明確な反意語なし"],collocations:["report identified avarice as a","The report identified avarice as a serious obstacle"]},
  avert:{pos:"verb",synonyms:["stave off","obviate"],antonyms:["明確な反意語なし"],collocations:["tried to avert the claim","Independent investigators tried to avert the claim before the"]},
  banal:{pos:"adjective",synonyms:["trite","hackneyed"],antonyms:["明確な反意語なし"],collocations:["Her banal explanation changed","Her banal explanation changed how the"]},
  belie:{pos:"verb",synonyms:["negate","contradict"],antonyms:["明確な反意語なし"],collocations:["policy could belie efforts to","The new policy could belie efforts to restore public"]},
  belligerent:{pos:"noun",synonyms:["warring","militant"],antonyms:["明確な反意語なし"],collocations:["the regime’s belligerent rhetoric could","warned that the regime’s belligerent rhetoric could destabilize the"]},
  bereft:{pos:"adjective",synonyms:["grief-stricken","sorrowing"],antonyms:["明確な反意語なし"],collocations:["considered an bereft approach to","what it considered an bereft approach to the problem"]},
  blatant:{pos:"adjective",synonyms:["unconcealed","conspicuous"],antonyms:["明確な反意語なし"],collocations:["Her blatant explanation changed","Her blatant explanation changed how the"]},
  boisterous:{pos:"adjective",synonyms:["rumbustious","rambunctious"],antonyms:["明確な反意語なし"],collocations:["response as boisterous during the","the government's response as boisterous during the national debate"]},
  bolster:{pos:"verb",synonyms:["strengthen","support"],antonyms:["undermine","weaken"],collocations:["bolster confidence","bolster the economy"]},
  brevity:{pos:"noun",synonyms:["briefness","transience"],antonyms:["明確な反意語なし"],collocations:["concern about brevity grew after","Public concern about brevity grew after the investigation"]},
  cajole:{pos:"verb",synonyms:["inveigle","wheedle"],antonyms:["明確な反意語なし"],collocations:["officials might cajole the principles","warned that officials might cajole the principles they had"]},
  callous:{pos:"adjective",synonyms:["insensitive","thick-skinned"],antonyms:["明確な反意語なし"],collocations:["response as callous during the","the government's response as callous during the national debate"]},
  camaraderie:{pos:"noun",synonyms:["good fellowship","comradeship"],antonyms:["明確な反意語なし"],collocations:["concern about camaraderie grew after","Public concern about camaraderie grew after the investigation"]},
  candid:{pos:"noun",synonyms:["unstudied","artless"],antonyms:["明確な反意語なし"],collocations:["gave a candid assessment of","The CEO gave a candid assessment of the company’s"]},
  capricious:{pos:"adjective",synonyms:["arbitrary","whimsical"],antonyms:["conscientious","rigorous"],collocations:["the CEO’s capricious decision-making style","alarmed by the CEO’s capricious decision-making style"]},
  catharsis:{pos:"noun",synonyms:["katharsis","abreaction"],antonyms:["明確な反意語なし"],collocations:["consequences of catharsis","the social consequences of catharsis"]},
  censure:{pos:"noun",synonyms:["reprimand","animadversion"],antonyms:["明確な反意語なし"],collocations:["voted to censure the official","The committee voted to censure the official for abusing"]},
  circumspect:{pos:"adjective",synonyms:["prudent","discreet"],antonyms:["明確な反意語なし"],collocations:["response as circumspect during the","the government's response as circumspect during the national debate"]},
  clandestine:{pos:"adjective",synonyms:["hole-and-corner","cloak-and-dagger"],antonyms:["明確な反意語なし"],collocations:["response as clandestine during the","the government's response as clandestine during the national debate"]},
  coalesce:{pos:"verb",synonyms:["merge","meld"],antonyms:["明確な反意語なし"],collocations:["tried to coalesce the claim","Independent investigators tried to coalesce the claim before the"]},
  coerce:{pos:"verb",synonyms:["force","pressure"],antonyms:["明確な反意語なし"],collocations:["officials might coerce the principles","warned that officials might coerce the principles they had"]},
  cogent:{pos:"adjective",synonyms:["influential","telling"],antonyms:["明確な反意語なし"],collocations:["response as cogent during the","the government's response as cogent during the national debate"]},
  coherent:{pos:"unknown",synonyms:["logical","rational"],antonyms:["incoherent"],collocations:["present a coherent alternative to","failed to present a coherent alternative to the policy"]},
  commensurate:{pos:"adjective",synonyms:["commensurable","proportionate"],antonyms:["incommensurate"],collocations:["considered an commensurate approach to","what it considered an commensurate approach to the problem"]},
  complacent:{pos:"unknown",synonyms:["self-satisfied","content"],antonyms:["明確な反意語なし"],collocations:["team became complacent after several","The team became complacent after several years of"]},
  complicity:{pos:"noun",synonyms:["complicit","abetment"],antonyms:["明確な反意語なし"],collocations:["consequences of complicity","the social consequences of complicity"]},
  concede:{pos:"verb",synonyms:["admit","acknowledge"],antonyms:["deny","contest"],collocations:["concede defeat","concede that ..."]},
  conciliatory:{pos:"adjective",synonyms:["compromising","yielding"],antonyms:["antagonistic","inflexible"],collocations:["response as conciliatory during the","the government's response as conciliatory during the national debate"]},
  conflagration:{pos:"noun",synonyms:["inferno","blaze"],antonyms:["明確な反意語なし"],collocations:["concern about conflagration grew after","Public concern about conflagration grew after the investigation"]},
  conscientious:{pos:"adjective",synonyms:["scrupulous","painstaking"],antonyms:["unconscientious"],collocations:["Her conscientious explanation changed","Her conscientious explanation changed how the"]},
  conspicuous:{pos:"unknown",synonyms:["obvious","unconcealed"],antonyms:["inconspicuous","invisible"],collocations:["was a conspicuous lack of","There was a conspicuous lack of evidence in"]},
  construe:{pos:"verb",synonyms:["interpret","infer"],antonyms:["明確な反意語なし"],collocations:["tried to construe the claim","Independent investigators tried to construe the claim before the"]},
  contemptuous:{pos:"adjective",synonyms:["disdainful","scornful"],antonyms:["明確な反意語なし"],collocations:["Her contemptuous explanation changed","Her contemptuous explanation changed how the"]},
  contentious:{pos:"adjective",synonyms:["controversial","disputative"],antonyms:["明確な反意語なし"],collocations:["the most contentious issues in","one of the most contentious issues in the election"]},
  contrite:{pos:"adjective",synonyms:["penitent","repentant"],antonyms:["明確な反意語なし"],collocations:["response as contrite during the","the government's response as contrite during the national debate"]},
  conundrum:{pos:"noun",synonyms:["brain-teaser","enigma"],antonyms:["明確な反意語なし"],collocations:["major policy conundrum","remains a major policy conundrum"]},
  copious:{pos:"adjective",synonyms:["plentiful","plenteous"],antonyms:["明確な反意語なし"],collocations:["considered an copious approach to","what it considered an copious approach to the problem"]},
  corroborate:{pos:"verb",synonyms:["validate","bear out"],antonyms:["negate","contradict"],collocations:["officials might corroborate the principles","warned that officials might corroborate the principles they had"]},
  credulous:{pos:"adjective",synonyms:["credible","overcredulous"],antonyms:["incredulous"],collocations:["response as credulous during the","the government's response as credulous during the national debate"]},
  culpable:{pos:"adjective",synonyms:["blameful","blameable"],antonyms:["明確な反意語なし"],collocations:["considered an culpable approach to","what it considered an culpable approach to the problem"]},
  curtail:{pos:"unknown",synonyms:["cut short","restrict"],antonyms:["明確な反意語なし"],collocations:["decided to curtail unnecessary expenses","The company decided to curtail unnecessary expenses"]},
  dearth:{pos:"noun",synonyms:["scarcity","shortage"],antonyms:["abundance","surplus"],collocations:["a dearth of evidence","a dearth of talent"]},
  debase:{pos:"verb",synonyms:["vitiate","demoralize"],antonyms:["明確な反意語なし"],collocations:["officials might debase the principles","warned that officials might debase the principles they had"]},
  debilitate:{pos:"verb",synonyms:["enfeeble","drain"],antonyms:["明確な反意語なし"],collocations:["policy could debilitate efforts to","The new policy could debilitate efforts to restore public"]},
  decry:{pos:"verb",synonyms:["condemn","objurgate"],antonyms:["明確な反意語なし"],collocations:["tried to decry the claim","Independent investigators tried to decry the claim before the"]},
  deference:{pos:"noun",synonyms:["respectfulness","respect"],antonyms:["明確な反意語なし"],collocations:["concern about deference grew after","Public concern about deference grew after the investigation"]},
  defunct:{pos:"noun",synonyms:["dead","inoperative"],antonyms:["明確な反意語なし"],collocations:["converted a defunct factory into","The city converted a defunct factory into a community"]},
  deleterious:{pos:"adjective",synonyms:["harmful","detrimental"],antonyms:["beneficial","harmless"],collocations:["deleterious effects","deleterious impact"]},
  delineate:{pos:"verb",synonyms:["outline","delimitate"],antonyms:["undelineated"],collocations:["officials might delineate the principles","warned that officials might delineate the principles they had"]},
  demure:{pos:"adjective",synonyms:["modest","overmodest"],antonyms:["明確な反意語なし"],collocations:["response as demure during the","the government's response as demure during the national debate"]},
  denigrate:{pos:"verb",synonyms:["calumniate","defame"],antonyms:["明確な反意語なし"],collocations:["tried to denigrate the claim","Independent investigators tried to denigrate the claim before the"]},
  deplore:{pos:"verb",synonyms:["lament","bemoan"],antonyms:["明確な反意語なし"],collocations:["officials might deplore the principles","warned that officials might deplore the principles they had"]},
  depravity:{pos:"noun",synonyms:["turpitude","corruption"],antonyms:["明確な反意語なし"],collocations:["report identified depravity as a","The report identified depravity as a serious obstacle"]},
  deride:{pos:"unknown",synonyms:["jeer","ridicule"],antonyms:["明確な反意語なし"],collocations:["began to deride the proposal","Critics began to deride the proposal as unrealistic"]},
  despondent:{pos:"adjective",synonyms:["hopeless","heartsick"],antonyms:["明確な反意語なし"],collocations:["Her despondent explanation changed","Her despondent explanation changed how the"]},
  destitute:{pos:"adjective",synonyms:["indigent","poor"],antonyms:["明確な反意語なし"],collocations:["were left destitute","many families were left destitute"]},
  detractor:{pos:"unknown",synonyms:["disparager","depreciator"],antonyms:["明確な反意語なし"],collocations:["his harshest detractor admitted that","Even his harshest detractor admitted that the plan"]},
  dexterous:{pos:"adjective",synonyms:["dextrous","adroit"],antonyms:["明確な反意語なし"],collocations:["response as dexterous during the","the government's response as dexterous during the national debate"]},
  didactic:{pos:"adjective",synonyms:["instructive","informative"],antonyms:["明確な反意語なし"],collocations:["considered an didactic approach to","what it considered an didactic approach to the problem"]},
  diffident:{pos:"adjective",synonyms:["timid","unsure"],antonyms:["明確な反意語なし"],collocations:["Her diffident explanation changed","Her diffident explanation changed how the"]},
  dilapidated:{pos:"adjective",synonyms:["ramshackle","damaged"],antonyms:["明確な反意語なし"],collocations:["response as dilapidated during the","the government's response as dilapidated during the national debate"]},
  diligent:{pos:"adjective",synonyms:["assiduous","industrious"],antonyms:["negligent"],collocations:["considered an diligent approach to","what it considered an diligent approach to the problem"]},
  discerning:{pos:"adjective",synonyms:["perceptive","percipient"],antonyms:["undiscerning"],collocations:["Her discerning explanation changed","Her discerning explanation changed how the"]},
  disconcert:{pos:"verb",synonyms:["discomfit","consternate"],antonyms:["明確な反意語なし"],collocations:["policy could disconcert efforts to","The new policy could disconcert efforts to restore public"]},
  discredit:{pos:"verb",synonyms:["disgrace","disrepute"],antonyms:["believe","repute"],collocations:["tried to discredit the claim","Independent investigators tried to discredit the claim before the"]},
  discrepancy:{pos:"unknown",synonyms:["divergence","disagreement"],antonyms:["明確な反意語なし"],collocations:["discovered a discrepancy between the","Auditors discovered a discrepancy between the records and"]},
  disdain:{pos:"verb",synonyms:["scorn","contempt"],antonyms:["明確な反意語なし"],collocations:["officials might disdain the principles","warned that officials might disdain the principles they had"]},
  disparage:{pos:"noun",synonyms:["belittle","pick at"],antonyms:["blandish","flatter"],collocations:["should not disparage citizens who","Political leaders should not disparage citizens who express legitimate"]},
  disseminate:{pos:"verb",synonyms:["propagate","diffuse"],antonyms:["明確な反意語なし"],collocations:["policy could disseminate efforts to","The new policy could disseminate efforts to restore public"]},
  dissuade:{pos:"unknown",synonyms:["deter","prevent"],antonyms:["persuade"],collocations:["tried to dissuade young people","Experts tried to dissuade young people from investing"]},
  dogmatic:{pos:"adjective",synonyms:["dogmatical","narrow-minded"],antonyms:["明確な反意語なし"],collocations:["considered an dogmatic approach to","what it considered an dogmatic approach to the problem"]},
  dubious:{pos:"adjective",synonyms:["questionable","doubtful"],antonyms:["明確な反意語なし"],collocations:["Her dubious explanation changed","Her dubious explanation changed how the"]},
  ebullient:{pos:"adjective",synonyms:["exuberant","high-spirited"],antonyms:["明確な反意語なし"],collocations:["response as ebullient during the","the government's response as ebullient during the national debate"]},
  eclectic:{pos:"adjective",synonyms:["eclecticist","discriminating"],antonyms:["明確な反意語なし"],collocations:["considered an eclectic approach to","what it considered an eclectic approach to the problem"]},
  edify:{pos:"verb",synonyms:["enlighten","build"],antonyms:["明確な反意語なし"],collocations:["officials might edify the principles","warned that officials might edify the principles they had"]},
  efficacy:{pos:"noun",synonyms:["efficaciousness","efficacious"],antonyms:["inefficacy","inefficaciousness"],collocations:["report identified efficacy as a","The report identified efficacy as a serious obstacle"]},
  egregious:{pos:"adjective",synonyms:["flagrant","gross"],antonyms:["明確な反意語なし"],collocations:["considered an egregious approach to","what it considered an egregious approach to the problem"]},
  elicit:{pos:"verb",synonyms:["evoke","draw out"],antonyms:["suppress","stifle"],collocations:["elicit a response","elicit information"]},
  elusive:{pos:"adjective",synonyms:["evasive","subtle"],antonyms:["明確な反意語なし"],collocations:["Her elusive explanation changed","Her elusive explanation changed how the"]},
  embellish:{pos:"verb",synonyms:["adorn","decorate"],antonyms:["uglify"],collocations:["policy could embellish efforts to","The new policy could embellish efforts to restore public"]},
  empirical:{pos:"adjective",synonyms:["experiential","existential"],antonyms:["theoretical","theoretic"],collocations:["considered an empirical approach to","what it considered an empirical approach to the problem"]},
  emulate:{pos:"verb",synonyms:["copy","mimic"],antonyms:["明確な反意語なし"],collocations:["try to emulate the management","Many startups try to emulate the management style of"]},
  encroach:{pos:"verb",synonyms:["infringe","impinge"],antonyms:["明確な反意語なし"],collocations:["officials might encroach the principles","warned that officials might encroach the principles they had"]},
  endemic:{pos:"adjective",synonyms:["autochthonous","autochthonic"],antonyms:["cosmopolitan","epidemic"],collocations:["response as endemic during the","the government's response as endemic during the national debate"]},
  enervate:{pos:"verb",synonyms:["unnerve","faze"],antonyms:["明確な反意語なし"],collocations:["tried to enervate the claim","Independent investigators tried to enervate the claim before the"]},
  enfranchise:{pos:"verb",synonyms:["affranchise","empower"],antonyms:["disenfranchise","disfranchise"],collocations:["officials might enfranchise the principles","warned that officials might enfranchise the principles they had"]},
  engender:{pos:"unknown",synonyms:["beget","breed"],antonyms:["明確な反意語なし"],collocations:["transparency can engender distrust among","Lack of transparency can engender distrust among citizens"]},
  enigmatic:{pos:"adjective",synonyms:["enigmatical","ambiguous"],antonyms:["明確な反意語なし"],collocations:["response as enigmatic during the","the government's response as enigmatic during the national debate"]},
  enmity:{pos:"noun",synonyms:["antagonism","hostility"],antonyms:["明確な反意語なし"],collocations:["concern about enmity grew after","Public concern about enmity grew after the investigation"]},
  entrench:{pos:"verb",synonyms:["trench","dig in"],antonyms:["明確な反意語なし"],collocations:["officials might entrench the principles","warned that officials might entrench the principles they had"]},
  ephemeral:{pos:"adjective",synonyms:["fleeting","transient"],antonyms:["enduring","permanent"],collocations:["ephemeral fame","ephemeral nature"]},
  equivocal:{pos:"unknown",synonyms:["ambiguous","ambivalent"],antonyms:["unequivocal","univocal"],collocations:["gave an equivocal answer when","The minister gave an equivocal answer when asked about"]},
  eradicate:{pos:"verb",synonyms:["extirpate","uproot"],antonyms:["明確な反意語なし"],collocations:["tried to eradicate the claim","Independent investigators tried to eradicate the claim before the"]},
  erratic:{pos:"adjective",synonyms:["fickle","unsettled"],antonyms:["明確な反意語なし"],collocations:["response as erratic during the","the government's response as erratic during the national debate"]},
  esoteric:{pos:"adjective",synonyms:["mystical","mystic"],antonyms:["exoteric"],collocations:["Her esoteric explanation changed","Her esoteric explanation changed how the"]},
  euphemism:{pos:"noun",synonyms:["understatement","rewording"],antonyms:["明確な反意語なし"],collocations:["report identified euphemism as a","The report identified euphemism as a serious obstacle"]},
  evince:{pos:"verb",synonyms:["show","express"],antonyms:["明確な反意語なし"],collocations:["tried to evince the claim","Independent investigators tried to evince the claim before the"]},
  exacerbate:{pos:"verb",synonyms:["aggravate","worsen"],antonyms:["alleviate","mitigate"],collocations:["exacerbate tensions","exacerbate the problem"]},
  exasperate:{pos:"verb",synonyms:["aggravate","infuriate"],antonyms:["ameliorate","improve"],collocations:["officials might exasperate the principles","warned that officials might exasperate the principles they had"]},
  exculpate:{pos:"verb",synonyms:["assoil","acquit"],antonyms:["convict"],collocations:["policy could exculpate efforts to","The new policy could exculpate efforts to restore public"]},
  exemplary:{pos:"unknown",synonyms:["worthy","cautionary"],antonyms:["明確な反意語なし"],collocations:["regarded as exemplary","was widely regarded as exemplary"]},
  exonerate:{pos:"unknown",synonyms:["discharge","exculpate"],antonyms:["convict"],collocations:["investigation helped exonerate the employee","The investigation helped exonerate the employee of wrongdoing"]},
  exorbitant:{pos:"adjective",synonyms:["immoderate","outrageous"],antonyms:["明確な反意語なし"],collocations:["considered an exorbitant approach to","what it considered an exorbitant approach to the problem"]},
  expedite:{pos:"verb",synonyms:["hasten","expeditiously"],antonyms:["明確な反意語なし"],collocations:["officials might expedite the principles","warned that officials might expedite the principles they had"]},
  extol:{pos:"verb",synonyms:["laud","exalt"],antonyms:["明確な反意語なし"],collocations:["policy could extol efforts to","The new policy could extol efforts to restore public"]},
  extraneous:{pos:"adjective",synonyms:["extrinsic","foreign"],antonyms:["明確な反意語なし"],collocations:["considered an extraneous approach to","what it considered an extraneous approach to the problem"]},
  fallacious:{pos:"adjective",synonyms:["deceitful","fraudulent"],antonyms:["明確な反意語なし"],collocations:["Her fallacious explanation changed","Her fallacious explanation changed how the"]},
  fastidious:{pos:"adjective",synonyms:["exacting","fussy"],antonyms:["unfastidious"],collocations:["was so fastidious that even","The editor was so fastidious that even minor punctuation"]},
  fervent:{pos:"adjective",synonyms:["perfervid","ardent"],antonyms:["明確な反意語なし"],collocations:["response as fervent during the","the government's response as fervent during the national debate"]},
  fiasco:{pos:"noun",synonyms:["debacle","chaos"],antonyms:["明確な反意語なし"],collocations:["public relations fiasco","into a public relations fiasco"]},
  flagrant:{pos:"adjective",synonyms:["egregious","gross"],antonyms:["明確な反意語なし"],collocations:["considered an flagrant approach to","what it considered an flagrant approach to the problem"]},
  flippant:{pos:"adjective",synonyms:["light-minded","frivolous"],antonyms:["明確な反意語なし"],collocations:["Her flippant explanation changed","Her flippant explanation changed how the"]},
  forfeit:{pos:"unknown",synonyms:["forfeiture","waive"],antonyms:["arrogate","claim"],collocations:["rules may forfeit their medals","violate the rules may forfeit their medals"]},
  formidable:{pos:"unknown",synonyms:["redoubtable","alarming"],antonyms:["明確な反意語なし"],collocations:["effort faces formidable political opposition","The reform effort faces formidable political opposition"]},
  fortuitous:{pos:"adjective",synonyms:["fortunate","uncaused"],antonyms:["明確な反意語なし"],collocations:["response as fortuitous during the","the government's response as fortuitous during the national debate"]},
  fractious:{pos:"adjective",synonyms:["nettlesome","irritable"],antonyms:["明確な反意語なし"],collocations:["considered an fractious approach to","what it considered an fractious approach to the problem"]},
  fraudulent:{pos:"adjective",synonyms:["deceitful","fallacious"],antonyms:["明確な反意語なし"],collocations:["detected several fraudulent transactions in","The bank detected several fraudulent transactions in the account"]},
  furtive:{pos:"adjective",synonyms:["sneaky","stealthy"],antonyms:["明確な反意語なし"],collocations:["Her furtive explanation changed","Her furtive explanation changed how the"]},
  galvanize:{pos:"verb",synonyms:["animate","startle"],antonyms:["明確な反意語なし"],collocations:["crisis helped galvanize young voters","The crisis helped galvanize young voters into participating"]},
  garrulous:{pos:"adjective",synonyms:["talkative","loquacious"],antonyms:["明確な反意語なし"],collocations:["response as garrulous during the","the government's response as garrulous during the national debate"]},
  germane:{pos:"adjective",synonyms:["relevant","related"],antonyms:["明確な反意語なし"],collocations:["considered an germane approach to","what it considered an germane approach to the problem"]},
  glib:{pos:"adjective",synonyms:["superficial","smooth-tongued"],antonyms:["明確な反意語なし"],collocations:["Her glib explanation changed","Her glib explanation changed how the"]},
  gratuitous:{pos:"adjective",synonyms:["gratis","free"],antonyms:["明確な反意語なし"],collocations:["response as gratuitous during the","the government's response as gratuitous during the national debate"]},
  hackneyed:{pos:"adjective",synonyms:["trite","banal"],antonyms:["明確な反意語なし"],collocations:["considered an hackneyed approach to","what it considered an hackneyed approach to the problem"]},
  haphazard:{pos:"adjective",synonyms:["hit-or-miss","random"],antonyms:["明確な反意語なし"],collocations:["Her haphazard explanation changed","Her haphazard explanation changed how the"]},
  harangue:{pos:"verb",synonyms:["ranting","rant"],antonyms:["明確な反意語なし"],collocations:["policy could harangue efforts to","The new policy could harangue efforts to restore public"]},
  heed:{pos:"verb",synonyms:["attentiveness","regard"],antonyms:["inattentiveness","heedlessness"],collocations:["tried to heed the claim","Independent investigators tried to heed the claim before the"]},
  heinous:{pos:"adjective",synonyms:["atrocious","evil"],antonyms:["明確な反意語なし"],collocations:["Her heinous explanation changed","Her heinous explanation changed how the"]},
  herald:{pos:"verb",synonyms:["announce","annunciate"],antonyms:["明確な反意語なし"],collocations:["policy could herald efforts to","The new policy could herald efforts to restore public"]},
  imminent:{pos:"adjective",synonyms:["immediate","impending"],antonyms:["明確な反意語なし"],collocations:["shortage was imminent","a water shortage was imminent"]},
  impede:{pos:"verb",synonyms:["hinder","obstruct"],antonyms:["facilitate","assist"],collocations:["impede progress","seriously impede"]},
  impetus:{pos:"unknown",synonyms:["impulsion","impulse"],antonyms:["明確な反意語なし"],collocations:["provided the impetus for political","Public outrage provided the impetus for political reform"]},
  inadvertent:{pos:"unknown",synonyms:["unintended","accidental"],antonyms:["明確な反意語なし"],collocations:["An inadvertent error in","An inadvertent error in the software"]},
  incumbent:{pos:"unknown",synonyms:["officeholder","superjacent"],antonyms:["明確な反意語なし"],collocations:["The incumbent mayor faces","The incumbent mayor faces a strong"]},
  indispensable:{pos:"unknown",synonyms:["critical","essential"],antonyms:["dispensable"],collocations:["data is indispensable for effective","Reliable data is indispensable for effective policymaking"]},
  indolent:{pos:"adjective",synonyms:["slothful","idle"],antonyms:["明確な反意語なし"],collocations:["considered an indolent approach to","what it considered an indolent approach to the problem"]},
  infallible:{pos:"adjective",synonyms:["inerrable","inerrant"],antonyms:["fallible"],collocations:["Her infallible explanation changed","Her infallible explanation changed how the"]},
  ingenuous:{pos:"adjective",synonyms:["naif","naive"],antonyms:["artful","disingenuous"],collocations:["response as ingenuous during the","the government's response as ingenuous during the national debate"]},
  inhibit:{pos:"verb",synonyms:["subdue","suppress"],antonyms:["明確な反意語なし"],collocations:["tried to inhibit the claim","Independent investigators tried to inhibit the claim before the"]},
  innocuous:{pos:"adjective",synonyms:["harmless","innoxious"],antonyms:["harmful","noxious"],collocations:["Her innocuous explanation changed","Her innocuous explanation changed how the"]},
  insidious:{pos:"adjective",synonyms:["pernicious","harmful"],antonyms:["明確な反意語なし"],collocations:["response as insidious during the","the government's response as insidious during the national debate"]},
  insolent:{pos:"adjective",synonyms:["impudent","brazen-faced"],antonyms:["明確な反意語なし"],collocations:["considered an insolent approach to","what it considered an insolent approach to the problem"]},
  intransigent:{pos:"noun",synonyms:["adamant","inflexible"],antonyms:["明確な反意語なし"],collocations:["sides remained intransigent","because both sides remained intransigent"]},
  intrepid:{pos:"adjective",synonyms:["brave","audacious"],antonyms:["明確な反意語なし"],collocations:["Her intrepid explanation changed","Her intrepid explanation changed how the"]},
  inundate:{pos:"unknown",synonyms:["deluge","submerge"],antonyms:["明確な反意語なし"],collocations:["agency was inundate with requests","The agency was inundate with requests after the"]},
  irascible:{pos:"adjective",synonyms:["quick-tempered","ill-natured"],antonyms:["明確な反意語なし"],collocations:["response as irascible during the","the government's response as irascible during the national debate"]},
  irrefutable:{pos:"adjective",synonyms:["undeniable","incontrovertible"],antonyms:["明確な反意語なし"],collocations:["considered an irrefutable approach to","what it considered an irrefutable approach to the problem"]},
  jettison:{pos:"verb",synonyms:["ditch","dump"],antonyms:["明確な反意語なし"],collocations:["officials might jettison the principles","warned that officials might jettison the principles they had"]},
  jubilant:{pos:"adjective",synonyms:["exulting","rejoicing"],antonyms:["明確な反意語なし"],collocations:["response as jubilant during the","the government's response as jubilant during the national debate"]},
  judicious:{pos:"adjective",synonyms:["wise","prudent"],antonyms:["明確な反意語なし"],collocations:["considered an judicious approach to","what it considered an judicious approach to the problem"]},
  laconic:{pos:"adjective",synonyms:["concise","pithy"],antonyms:["bombastic","long-winded"],collocations:["His laconic reply made","His laconic reply made it difficult"]},
  languid:{pos:"adjective",synonyms:["lethargic","languorous"],antonyms:["明確な反意語なし"],collocations:["Her languid explanation changed","Her languid explanation changed how the"]},
  laud:{pos:"verb",synonyms:["extol","exalt"],antonyms:["明確な反意語なし"],collocations:["policy could laud efforts to","The new policy could laud efforts to restore public"]},
  lethargic:{pos:"adjective",synonyms:["logy","languid"],antonyms:["energetic"],collocations:["considered an lethargic approach to","what it considered an lethargic approach to the problem"]},
  lucid:{pos:"adjective",synonyms:["perspicuous","crystal clear"],antonyms:["明確な反意語なし"],collocations:["Her lucid explanation changed","Her lucid explanation changed how the"]},
  lucrative:{pos:"unknown",synonyms:["profitable","remunerative"],antonyms:["明確な反意語なし"],collocations:["become a lucrative market for","energy has become a lucrative market for investors"]},
  magnanimous:{pos:"unknown",synonyms:["generous","greathearted"],antonyms:["明確な反意語なし"],collocations:["She was magnanimous in victory","She was magnanimous in victory and praised"]},
  malevolent:{pos:"adjective",synonyms:["malicious","evil"],antonyms:["benevolent","good"],collocations:["considered an malevolent approach to","what it considered an malevolent approach to the problem"]},
  malleable:{pos:"adjective",synonyms:["elastic","ductile"],antonyms:["明確な反意語なし"],collocations:["Her malleable explanation changed","Her malleable explanation changed how the"]},
  mendacious:{pos:"adjective",synonyms:["untruthful","lying"],antonyms:["明確な反意語なし"],collocations:["response as mendacious during the","the government's response as mendacious during the national debate"]},
  mercurial:{pos:"adjective",synonyms:["quicksilver","changeful"],antonyms:["明確な反意語なし"],collocations:["response as mercurial during the","the government's response as mercurial during the national debate"]},
  meticulous:{pos:"unknown",synonyms:["punctilious","fastidious"],antonyms:["明確な反意語なし"],collocations:["conducted a meticulous review of","The scientist conducted a meticulous review of the experimental"]},
  mitigate:{pos:"verb",synonyms:["alleviate","lessen"],antonyms:["aggravate","intensify"],collocations:["mitigate risk","mitigate the effects"]},
  mollify:{pos:"verb",synonyms:["lenify","appease"],antonyms:["明確な反意語なし"],collocations:["officials might mollify the principles","warned that officials might mollify the principles they had"]},
  moratorium:{pos:"unknown",synonyms:["waiver","embargo"],antonyms:["明確な反意語なし"],collocations:["imposed a moratorium on new","The city imposed a moratorium on new hotel construction"]},
  morose:{pos:"adjective",synonyms:["glum","sullen"],antonyms:["明確な反意語なし"],collocations:["considered an morose approach to","what it considered an morose approach to the problem"]},
  mundane:{pos:"noun",synonyms:["worldly","everyday"],antonyms:["明確な反意語なし"],collocations:["automate many mundane tasks that","AI can automate many mundane tasks that once consumed"]},
  nebulous:{pos:"adjective",synonyms:["nebulose","cloudy"],antonyms:["明確な反意語なし"],collocations:["response as nebulous during the","the government's response as nebulous during the national debate"]},
  nefarious:{pos:"adjective",synonyms:["villainous","wicked"],antonyms:["明確な反意語なし"],collocations:["considered an nefarious approach to","what it considered an nefarious approach to the problem"]},
  obdurate:{pos:"verb",synonyms:["obstinate","hardhearted"],antonyms:["明確な反意語なし"],collocations:["board remained obdurate despite repeated","The board remained obdurate despite repeated warnings from"]},
  obfuscate:{pos:"unknown",synonyms:["overshadow","darken"],antonyms:["elucidate","clarify"],collocations:["jargon to obfuscate the real","used technical jargon to obfuscate the real issue"]},
  oblivious:{pos:"adjective",synonyms:["unaware","inattentive"],antonyms:["明確な反意語なし"],collocations:["considered an oblivious approach to","what it considered an oblivious approach to the problem"]},
  obsequious:{pos:"adjective",synonyms:["bootlicking","sycophantic"],antonyms:["明確な反意語なし"],collocations:["Her obsequious explanation changed","Her obsequious explanation changed how the"]},
  onerous:{pos:"adjective",synonyms:["demanding","difficult"],antonyms:["明確な反意語なし"],collocations:["were too onerous","reporting rules were too onerous"]},
  opulent:{pos:"adjective",synonyms:["sumptuous","luxurious"],antonyms:["明確な反意語なし"],collocations:["Her opulent explanation changed","Her opulent explanation changed how the"]},
  ostensible:{pos:"unknown",synonyms:["ostensive","seeming"],antonyms:["明確な反意語なし"],collocations:["The ostensible reason for","The ostensible reason for the policy"]},
  ostracize:{pos:"verb",synonyms:["blackball","banish"],antonyms:["明確な反意語なし"],collocations:["tried to ostracize the claim","Independent investigators tried to ostracize the claim before the"]},
  palpable:{pos:"adjective",synonyms:["tangible","perceptible"],antonyms:["impalpable"],collocations:["Her palpable explanation changed","Her palpable explanation changed how the"]},
  parochial:{pos:"unknown",synonyms:["provincial","insular"],antonyms:["明確な反意語なし"],collocations:["took a parochial view of","The committee took a parochial view of a global"]},
  perfunctory:{pos:"adjective",synonyms:["automatic","cursory"],antonyms:["careful","complete"],collocations:["issued a perfunctory apology that","The company issued a perfunctory apology that failed to"]},
  pernicious:{pos:"adjective",synonyms:["harmful","noxious"],antonyms:["明確な反意語なし"],collocations:["Her pernicious explanation changed","Her pernicious explanation changed how the"]},
  perpetuate:{pos:"unknown",synonyms:["continuity","permanent"],antonyms:["明確な反意語なし"],collocations:["policy can perpetuate social inequality","Poor education policy can perpetuate social inequality"]},
  placate:{pos:"verb",synonyms:["pacify","appease"],antonyms:["明確な反意語なし"],collocations:["policy could placate efforts to","The new policy could placate efforts to restore public"]},
  plausible:{pos:"adjective",synonyms:["likely","probable"],antonyms:["implausible","improbable"],collocations:["explanation sounded plausible but lacked","His explanation sounded plausible but lacked supporting evidence"]},
  pragmatic:{pos:"noun",synonyms:["pragmatical","practical"],antonyms:["明確な反意語なし"],collocations:["A more pragmatic approach is","A more pragmatic approach is needed to"]},
  precarious:{pos:"adjective",synonyms:["parlous","dangerous"],antonyms:["明確な反意語なし"],collocations:["Her precarious explanation changed","Her precarious explanation changed how the"]},
  precipitate:{pos:"verb",synonyms:["hasty","hurried"],antonyms:["明確な反意語なし"],collocations:["policy could precipitate efforts to","The new policy could precipitate efforts to restore public"]},
  precipitous:{pos:"unknown",synonyms:["abrupt","sharp"],antonyms:["明確な反意語なし"],collocations:["suffered a precipitous decline in","The company suffered a precipitous decline in sales after"]},
  preclude:{pos:"verb",synonyms:["prevent","forbid"],antonyms:["明確な反意語なし"],collocations:["tried to preclude the claim","Independent investigators tried to preclude the claim before the"]},
  predicament:{pos:"unknown",synonyms:["quandary","plight"],antonyms:["明確な反意語なし"],collocations:["a difficult predicament","company in a difficult predicament"]},
  prescient:{pos:"unknown",synonyms:["discerning","prescious"],antonyms:["明確な反意語なし"],collocations:["proved remarkably prescient","cybersecurity risks proved remarkably prescient"]},
  presumptuous:{pos:"adjective",synonyms:["assumptive","assuming"],antonyms:["明確な反意語なし"],collocations:["response as presumptuous during the","the government's response as presumptuous during the national debate"]},
  prodigal:{pos:"adjective",synonyms:["lavish","profligate"],antonyms:["明確な反意語なし"],collocations:["Her prodigal explanation changed","Her prodigal explanation changed how the"]},
  proliferate:{pos:"verb",synonyms:["spread","extend"],antonyms:["明確な反意語なし"],collocations:["information can proliferate rapidly during","False information can proliferate rapidly during a national"]},
  prolific:{pos:"adjective",synonyms:["fecund","productive"],antonyms:["明確な反意語なし"],collocations:["response as prolific during the","the government's response as prolific during the national debate"]},
  propensity:{pos:"noun",synonyms:["tendency","proclivity"],antonyms:["明確な反意語なし"],collocations:["concern about propensity grew after","Public concern about propensity grew after the investigation"]},
  propitiate:{pos:"verb",synonyms:["appease","repropitiate"],antonyms:["明確な反意語なし"],collocations:["officials might propitiate the principles","warned that officials might propitiate the principles they had"]},
  proponent:{pos:"unknown",synonyms:["advocate","exponent"],antonyms:["明確な反意語なし"],collocations:["a strong proponent of stricter","She is a strong proponent of stricter environmental protection"]},
  proscribe:{pos:"verb",synonyms:["forbid","prohibit"],antonyms:["countenance","allow"],collocations:["policy could proscribe efforts to","The new policy could proscribe efforts to restore public"]},
  quandary:{pos:"noun",synonyms:["predicament","dilemma"],antonyms:["明確な反意語なし"],collocations:["report identified quandary as a","The report identified quandary as a serious obstacle"]},
  quell:{pos:"verb",synonyms:["squelch","stay"],antonyms:["明確な反意語なし"],collocations:["tried to quell the claim","Independent investigators tried to quell the claim before the"]},
  quixotic:{pos:"unknown",synonyms:["romantic","wild-eyed"],antonyms:["明確な反意語なし"],collocations:["noble but quixotic","overnight was noble but quixotic"]},
  ramification:{pos:"unknown",synonyms:["branching","fork"],antonyms:["明確な反意語なし"],collocations:["have serious ramification for future","decision could have serious ramification for future trade negotiations"]},
  rancor:{pos:"unknown",synonyms:["resentment","bitterness"],antonyms:["明確な反意語なし"],collocations:["by personal rancor rather than","was marked by personal rancor rather than reasoned argument"]},
  ravenous:{pos:"adjective",synonyms:["ravening","rapacious"],antonyms:["明確な反意語なし"],collocations:["response as ravenous during the","the government's response as ravenous during the national debate"]},
  recalcitrant:{pos:"noun",synonyms:["refractory","defiant"],antonyms:["明確な反意語なし"],collocations:["manage a recalcitrant student who","struggled to manage a recalcitrant student who ignored every"]},
  reclusive:{pos:"adjective",synonyms:["secluded","private"],antonyms:["明確な反意語なし"],collocations:["response as reclusive during the","the government's response as reclusive during the national debate"]},
  reconcile:{pos:"verb",synonyms:["settle","conciliate"],antonyms:["明確な反意語なし"],collocations:["tried to reconcile the claim","Independent investigators tried to reconcile the claim before the"]},
  rectify:{pos:"unknown",synonyms:["remedy","amend"],antonyms:["明確な反意語なし"],collocations:["promised to rectify the accounting","The company promised to rectify the accounting error immediately"]},
  redundant:{pos:"adjective",synonyms:["superfluous","extra"],antonyms:["明確な反意語なし"],collocations:["considered an redundant approach to","what it considered an redundant approach to the problem"]},
  relegate:{pos:"unknown",synonyms:["banish","submit"],antonyms:["advance","promote"],collocations:["issue was relegate to the","The issue was relegate to the end of"]},
  relinquish:{pos:"verb",synonyms:["give up","quit"],antonyms:["明確な反意語なし"],collocations:["officials might relinquish the principles","warned that officials might relinquish the principles they had"]},
  reprehensible:{pos:"adjective",synonyms:["condemnable","criminal"],antonyms:["明確な反意語なし"],collocations:["response as reprehensible during the","the government's response as reprehensible during the national debate"]},
  repudiate:{pos:"verb",synonyms:["contradict","deny"],antonyms:["明確な反意語なし"],collocations:["tried to repudiate the controversial","senator quickly tried to repudiate the controversial remarks made"]},
  rescind:{pos:"verb",synonyms:["revoke","annul"],antonyms:["明確な反意語なし"],collocations:["tried to rescind the claim","Independent investigators tried to rescind the claim before the"]},
  resilient:{pos:"adjective",synonyms:["robust","adaptable"],antonyms:["fragile","vulnerable"],collocations:["a resilient economy","remarkably resilient"]},
  reticent:{pos:"adjective",synonyms:["reserved","taciturn"],antonyms:["明確な反意語なし"],collocations:["Her reticent explanation changed","Her reticent explanation changed how the"]},
  retribution:{pos:"noun",synonyms:["vengeance","revenge"],antonyms:["明確な反意語なし"],collocations:["consequences of retribution","the social consequences of retribution"]},
  reverent:{pos:"adjective",synonyms:["reverential","worshipful"],antonyms:["irreverent"],collocations:["considered an reverent approach to","what it considered an reverent approach to the problem"]},
  sagacious:{pos:"adjective",synonyms:["sapient","wise"],antonyms:["明確な反意語なし"],collocations:["response as sagacious during the","the government's response as sagacious during the national debate"]},
  salient:{pos:"noun",synonyms:["conspicuous","outstanding"],antonyms:["reentrant","re-entrant"],collocations:["The most salient feature of","The most salient feature of the report"]},
  sanguine:{pos:"unknown",synonyms:["rubicund","ruddy"],antonyms:["明確な反意語なし"],collocations:["Analysts remain sanguine about the","Analysts remain sanguine about the company’s long-term"]},
  sardonic:{pos:"adjective",synonyms:["sarcastic","wry"],antonyms:["明確な反意語なし"],collocations:["considered an sardonic approach to","what it considered an sardonic approach to the problem"]},
  scrupulous:{pos:"adjective",synonyms:["conscientious","painstaking"],antonyms:["unscrupulous"],collocations:["Her scrupulous explanation changed","Her scrupulous explanation changed how the"]},
  scrutinize:{pos:"verb",synonyms:["examine","inspect"],antonyms:["overlook","ignore"],collocations:["scrutinize the evidence","closely scrutinize"]},
  sporadic:{pos:"adjective",synonyms:["intermittent","isolated"],antonyms:["continual"],collocations:["Her sporadic explanation changed","Her sporadic explanation changed how the"]},
  spurious:{pos:"adjective",synonyms:["inauthentic","counterfeit"],antonyms:["明確な反意語なし"],collocations:["response as spurious during the","the government's response as spurious during the national debate"]},
  staunch:{pos:"adjective",synonyms:["steadfast","constant"],antonyms:["明確な反意語なし"],collocations:["considered an staunch approach to","what it considered an staunch approach to the problem"]},
  stringent:{pos:"adjective",synonyms:["rigorous","tight"],antonyms:["明確な反意語なし"],collocations:["government introduced stringent rules to","The government introduced stringent rules to prevent financial"]},
  substantiate:{pos:"verb",synonyms:["verify","corroborate"],antonyms:["refute","disprove"],collocations:["substantiate a claim","substantiate allegations"]},
  succinct:{pos:"adjective",synonyms:["concise","summary"],antonyms:["明確な反意語なし"],collocations:["considered an succinct approach to","what it considered an succinct approach to the problem"]},
  superfluous:{pos:"adjective",synonyms:["extra","excess"],antonyms:["明確な反意語なし"],collocations:["Her superfluous explanation changed","Her superfluous explanation changed how the"]},
  suppress:{pos:"verb",synonyms:["repress","subdue"],antonyms:["明確な反意語なし"],collocations:["policy could suppress efforts to","The new policy could suppress efforts to restore public"]},
  surreptitious:{pos:"unknown",synonyms:["stealthy","sneaky"],antonyms:["明確な反意語なし"],collocations:["held a surreptitious meeting before","The executives held a surreptitious meeting before the announcement"]},
  tacit:{pos:"unknown",synonyms:["silent","inexplicit"],antonyms:["明確な反意語なし"],collocations:["was a tacit agreement not","There was a tacit agreement not to discuss"]},
  tenacious:{pos:"adjective",synonyms:["pertinacious","dogged"],antonyms:["明確な反意語なし"],collocations:["Her tenacious explanation changed","Her tenacious explanation changed how the"]},
  tenuous:{pos:"adjective",synonyms:["weak","flimsy"],antonyms:["strong","substantial"],collocations:["a tenuous link","a tenuous argument"]},
  tirade:{pos:"noun",synonyms:["broadside","philippic"],antonyms:["明確な反意語なし"],collocations:["concern about tirade grew after","Public concern about tirade grew after the investigation"]},
  transient:{pos:"adjective",synonyms:["fugacious","passing"],antonyms:["immanent","subjective"],collocations:["Her transient explanation changed","Her transient explanation changed how the"]},
  truculent:{pos:"unknown",synonyms:["aggressive","hostile"],antonyms:["明確な反意語なし"],collocations:["The negotiator’s truculent tone made","The negotiator’s truculent tone made compromise impossible"]},
  turbulent:{pos:"adjective",synonyms:["tumultuous","riotous"],antonyms:["明確な反意語なし"],collocations:["response as turbulent during the","the government's response as turbulent during the national debate"]},
  ubiquitous:{pos:"adjective",synonyms:["omnipresent","pervasive"],antonyms:["rare","scarce"],collocations:["increasingly ubiquitous","ubiquitous presence"]},
  unequivocal:{pos:"adjective",synonyms:["unambiguous","unquestionable"],antonyms:["ambiguous","equivocal"],collocations:["considered an unequivocal approach to","what it considered an unequivocal approach to the problem"]},
  unprecedented:{pos:"adjective",synonyms:["unexampled","new"],antonyms:["precedented"],collocations:["considered an unprecedented approach to","what it considered an unprecedented approach to the problem"]},
  untenable:{pos:"unknown",synonyms:["indefensible","unreasonable"],antonyms:["明確な反意語なし"],collocations:["position became untenable after new","The minister’s position became untenable after new evidence emerged"]},
  vacillate:{pos:"verb",synonyms:["stagger","blow hot and cold"],antonyms:["明確な反意語なし"],collocations:["continued to vacillate between two","The committee continued to vacillate between two competing proposals"]},
  vaunted:{pos:"verb",synonyms:["boast","brag"],antonyms:["明確な反意語なし"],collocations:["The company’s vaunted security system","The company’s vaunted security system failed during"]},
  venerate:{pos:"verb",synonyms:["reverence","revere"],antonyms:["明確な反意語なし"],collocations:["policy could venerate efforts to","The new policy could venerate efforts to restore public"]},
  vicarious:{pos:"adjective",synonyms:["secondary","ancillary"],antonyms:["明確な反意語なし"],collocations:["response as vicarious during the","the government's response as vicarious during the national debate"]},
  vindicate:{pos:"verb",synonyms:["justify","exonerate"],antonyms:["condemn","implicate"],collocations:["vindicate a decision","feel vindicated"]},
  virulent:{pos:"adjective",synonyms:["venomous","toxic"],antonyms:["avirulent"],collocations:["Her virulent explanation changed","Her virulent explanation changed how the"]},
  vitriolic:{pos:"adjective",synonyms:["sulfurous","sulphurous"],antonyms:["明確な反意語なし"],collocations:["response as vitriolic during the","the government's response as vitriolic during the national debate"]},
  vociferous:{pos:"unknown",synonyms:["clamorous","clamourous"],antonyms:["明確な反意語なし"],collocations:["There was vociferous opposition to","There was vociferous opposition to the proposed"]},
  volatile:{pos:"adjective",synonyms:["vaporific","volatilizable"],antonyms:["nonvolatile","nonvolatilizable"],collocations:["response as volatile during the","the government's response as volatile during the national debate"]},
  wane:{pos:"verb",synonyms:["decline","go down"],antonyms:["full","rise"],collocations:["officials might wane the principles","warned that officials might wane the principles they had"]},
  wary:{pos:"adjective",synonyms:["cautious","vigilant"],antonyms:["trusting","careless"],collocations:["wary of change","remain wary"]},
  watershed:{pos:"noun",synonyms:["water parting","divide"],antonyms:["明確な反意語なし"],collocations:["report identified watershed as a","The report identified watershed as a serious obstacle"]},
  whimsical:{pos:"adjective",synonyms:["capricious","impulsive"],antonyms:["明確な反意語なし"],collocations:["considered an whimsical approach to","what it considered an whimsical approach to the problem"]},
  withstand:{pos:"verb",synonyms:["stand firm","hold out"],antonyms:["surrender","give up"],collocations:["tried to withstand the claim","Independent investigators tried to withstand the claim before the"]},
  yearn:{pos:"verb",synonyms:["hanker","ache"],antonyms:["明確な反意語なし"],collocations:["tried to yearn the claim","Independent investigators tried to yearn the claim before the"]},
  zealot:{pos:"noun",synonyms:["partisan","fanatic"],antonyms:["明確な反意語なし"],collocations:["consequences of zealot","the social consequences of zealot"]},
  zealous:{pos:"unknown",synonyms:["avid","enthusiastic"],antonyms:["明確な反意語なし"],collocations:["is a zealous advocate of","She is a zealous advocate of education reform"]}
};
(window.EIKEN_WORDS||[]).forEach(function(word){
  var detail=DETAILS[word.w]||{};
  word.pos=detail.pos||word.p||'';
  word.synonyms=detail.synonyms||[];
  word.antonyms=detail.antonyms||[];
  word.collocations=detail.collocations||[];
  delete word.u;
});
})();
