const DATA=[
['aberration','逸脱、異常','The sudden drop in voter turnout was treated as an ____ rather than a long-term trend.'],
['acrimonious','辛辣な、とげとげしい','The debate became so ____ that the moderator had to intervene several times.'],
['anomaly','異例、例外的事象','Researchers found an ____ in the data that could not be explained by the existing theory.'],
['assuage','和らげる、鎮める','The prime minister tried to ____ public anxiety after the cyberattack.'],
['austere','質素な、厳格な','The new budget reflects an ____ approach to government spending.'],
['belligerent','好戦的な、攻撃的な','The diplomat warned that the regime’s ____ rhetoric could destabilize the region.'],
['bolster','強化する、支える','The new evidence helped ____ the argument for stricter environmental regulations.'],
['capricious','気まぐれな、予測不能な','Investors were alarmed by the CEO’s ____ decision-making style.'],
['censure','厳しく非難する','The committee voted to ____ the official for abusing his authority.'],
['concede','認める、譲歩する','Even supporters of the policy had to ____ that its implementation was flawed.'],
['dearth','不足、欠乏','A ____ of qualified teachers has become a serious problem in rural areas.'],
['deleterious','有害な','Excessive screen time can have ____ effects on children’s sleep patterns.'],
['disparage','けなす、見くびる','Political leaders should not ____ citizens who express legitimate concerns.'],
['elicit','引き出す','The documentary managed to ____ sympathy from viewers across the country.'],
['emulate','見習う、まねる','Many startups try to ____ the management style of successful technology firms.'],
['ephemeral','短命の、束の間の','Public enthusiasm for new social media trends is often ____.'],
['exacerbate','悪化させる','Poor communication can ____ tensions between management and employees.'],
['fastidious','非常に几帳面な','The editor was so ____ that even minor punctuation errors irritated her.'],
['galvanize','奮起させる','The crisis helped ____ young voters into participating in the election.'],
['intransigent','妥協しない','Negotiations collapsed because both sides remained ____.'],
['laconic','簡潔な、口数の少ない','His ____ reply made it difficult to understand what he really thought.'],
['mitigate','軽減する','Urban planners planted more trees to ____ the impact of extreme heat.'],
['obdurate','頑固な','The board remained ____ despite repeated warnings from experts.'],
['perfunctory','おざなりの','The company issued a ____ apology that failed to satisfy the public.'],
['proliferate','急増する','False information can ____ rapidly during a national emergency.'],
['recalcitrant','反抗的な','The teacher struggled to manage a ____ student who ignored every instruction.'],
['repudiate','拒絶する','The senator quickly tried to ____ the controversial remarks made by his adviser.'],
['resilient','回復力のある','Small businesses proved surprisingly ____ after the natural disaster.'],
['scrutinize','精査する','Journalists must ____ official statements before reporting them as facts.'],
['tenuous','根拠の薄い','The connection between the policy and the economic recovery remains ____.'],
['ubiquitous','至る所にある','Smartphones have become ____ in modern urban life.'],
['vacillate','揺れ動く','The committee continued to ____ between two competing proposals.'],
['vindicate','正当性を証明する','The final results seemed to ____ her controversial decision.'],
['wary','警戒している','Consumers are increasingly ____ of companies that collect excessive personal data.'],
['onerous','負担の重い','Small firms complained that the new reporting rules were too ____.'],
['destitute','極貧の','After losing their homes, many families were left ____.'],
['amnesty','恩赦','The government announced an ____ for minor tax violations.'],
['conundrum','難問','Balancing innovation and privacy remains a major policy ____.'],
['contentious','議論を呼ぶ','Immigration has become one of the most ____ issues in the election.'],
['candid','率直な','The CEO gave a ____ assessment of the company’s weaknesses.'],
['mundane','ありふれた','AI can automate many ____ tasks that once consumed workers’ time.'],
['fiasco','大失敗','The poorly planned launch turned into a public relations ____.'],
['defunct','廃止された','The city converted a ____ factory into a community center.'],
['vaunted','自慢の','The company’s ____ security system failed during the cyberattack.'],
['fraudulent','詐欺的な','The bank detected several ____ transactions in the account.'],
['stringent','厳格な','The government introduced ____ rules to prevent financial misconduct.'],
['pragmatic','実用的な','A more ____ approach is needed to solve the housing shortage.'],
['salient','顕著な','The most ____ feature of the report is its emphasis on inequality.'],
['imminent','差し迫った','Officials warned that a water shortage was ____.'],
['plausible','もっともらしい','His explanation sounded ____ but lacked supporting evidence.'],
['arbitrary','恣意的な','The court ruled that the restrictions were ____ and unfair.'],
['coherent','一貫した','The opposition failed to present a ____ alternative to the policy.'],
['ambiguous','曖昧な','The contract contained ____ language that led to disagreement.'],
['conspicuous','目立つ','There was a ____ lack of evidence in the official report.'],
['lucrative','儲かる','Renewable energy has become a ____ market for investors.'],
['precipitous','急激な','The company suffered a ____ decline in sales after the scandal.'],
['untenable','維持できない','The minister’s position became ____ after new evidence emerged.'],
['indispensable','不可欠な','Reliable data is ____ for effective policymaking.'],
['meticulous','細心の','The scientist conducted a ____ review of the experimental results.'],
['formidable','手ごわい','The reform effort faces ____ political opposition.'],
['inadvertent','不注意の','An ____ error in the software caused the outage.'],
['complacent','自己満足した','The team became ____ after several years of strong performance.'],
['exemplary','模範的な','Her leadership during the crisis was widely regarded as ____.'],
['discrepancy','不一致','Auditors discovered a ____ between the records and the actual inventory.'],
['ramification','波及効果','The decision could have serious ____ for future trade negotiations.'],
['predicament','苦境','The sudden rise in costs placed the company in a difficult ____.'],
['proponent','支持者','She is a strong ____ of stricter environmental protection.'],
['detractor','批判者','Even his harshest ____ admitted that the plan had some merit.'],
['impetus','推進力','Public outrage provided the ____ for political reform.'],
['moratorium','一時停止','The city imposed a ____ on new hotel construction.'],
['adversity','逆境','The community showed remarkable strength in the face of ____.'],
['alleviate','緩和する','The new subsidy is intended to ____ the burden on low-income families.'],
['curtail','削減する','The company decided to ____ unnecessary expenses.'],
['deride','嘲笑する','Critics began to ____ the proposal as unrealistic.'],
['dissuade','思いとどまらせる','Experts tried to ____ young people from investing in risky schemes.'],
['engender','生じさせる','Lack of transparency can ____ distrust among citizens.'],
['forfeit','失う','Athletes who violate the rules may ____ their medals.'],
['impede','妨げる','Excessive bureaucracy can ____ economic growth.'],
['obfuscate','分かりにくくする','The official used technical jargon to ____ the real issue.'],
['perpetuate','永続させる','Poor education policy can ____ social inequality.'],
['rectify','是正する','The company promised to ____ the accounting error immediately.'],
['substantiate','立証する','The journalist could not ____ the allegations with reliable evidence.'],
['surreptitious','秘密の','The executives held a ____ meeting before the announcement.'],
['tacit','暗黙の','There was a ____ agreement not to discuss the issue in public.'],
['ostensible','表向きの','The ____ reason for the policy was safety, but cost was the real concern.'],
['equivocal','曖昧な','The minister gave an ____ answer when asked about the scandal.'],
['incumbent','現職の','The ____ mayor faces a strong challenge in the upcoming election.'],
['magnanimous','寛大な','She was ____ in victory and praised her opponent.'],
['parochial','視野の狭い','The committee took a ____ view of a global problem.'],
['prescient','先見の明がある','Her warning about cybersecurity risks proved remarkably ____.'],
['quixotic','非現実的な','The plan to eliminate poverty overnight was noble but ____.'],
['rancor','深い恨み','The debate was marked by personal ____ rather than reasoned argument.'],
['relegate','格下げする','The issue was ____ to the end of the agenda.'],
['sanguine','楽観的な','Analysts remain ____ about the company’s long-term prospects.'],
['truculent','攻撃的な','The negotiator’s ____ tone made compromise impossible.'],
['vociferous','声高な','There was ____ opposition to the proposed tax increase.'],
['zealous','熱心な','She is a ____ advocate of education reform.'],
['abate','弱まる','Public anger did not ____ even after the minister apologized.'],
['inundate','殺到させる','The agency was ____ with requests after the disaster.'],
['exonerate','免罪する','The investigation helped ____ the employee of wrongdoing.']
];
window.EIKEN_WORDS=DATA.map(function(a,i){var n=DATA.length;var opts=[a[0],DATA[(i+17)%n][0],DATA[(i+39)%n][0],DATA[(i+61)%n][0]];return{w:a[0],p:'',m:a[1],j:a[1],s:a[2],o:opts,u:a[0]+' は英検1級Part 1・読解・Speakingで使える重要語です。'}});
